// Created by Crowbar 0.74

// Stored modelname (without quotes): "valve/models/garbagegibs.mdl"
$modelname "garbagegibs.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "parts"
{
	studio "waxpaper"
	studio "waxpaper2"
	studio "wad"
	studio "wad2"
	studio "styrocup"
	studio "sandwich"
	studio "apple"
	studio "banana"
	studio "newspaper"
	studio "envelope1"
	studio "envelope2"
	studio "can"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Line01" -12.19 -7.97 -0.11 9.41 10.47 5.54
$hbox 0 "GeoSphere01" -3.97 -2.47 -1.02 2.12 2.45 3.7
$hbox 0 "Cylinder01" -12.22 -2.93 0 6.69 2.92 20.360001
$hbox 0 "Line02" -4.2 -3.62 -1.82 4.29 5.51 1.19
$hbox 0 "Sphere01" -1.89 -1.89 -2.83 2.14 2.14 2.26
$hbox 0 "Box01" -7.26 -4.3 -3.37 1.76 6.48 0
$hbox 0 "Rectangle01" -7.19 -10.8 0 7.2 10.8 1.08

$sequence "idle1" {
	"garbagegibs_anims\idle1"
	fps 30
}
