// Created by Crowbar 0.74

// Stored modelname (without quotes): "valve/models/rip.mdl"
$modelname "rip.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "RIP1_Template_Biped1"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bone02" -3.3 0 -0.41 2.35 6.028251 1.3
$hbox 0 "Bone03" -0.71 0 -2.42 2.63 12.59 0
$hbox 0 "Bone04" -2.17 0 0 0.88 7.57 2.3
$hbox 0 "Bone05" 0 0 0 3.26 9.38 2.26
$hbox 0 "Bone06" -0.93 0 -1.79 1.35 4.04 0
$hbox 0 "Bone07" -0.59 0 0 1.97 3.64 2.29

$sequence "idle1" {
	"rip_anims\idle1"
	fps 10
}
