// Created by Crowbar 0.74

// Stored modelname (without quotes): "valve/models/w_gauss.mdl"
$modelname "w_gauss.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "w_gauss"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box02" -40.860001 -9.77 -6.21 31.690001 7.93 7.08

$sequence "stayput" {
	"w_gauss_anims\stayput"
	fps 30
}
$sequence "onside" {
	"w_gauss_anims\onside"
	fps 30
}
