// Created by Crowbar 0.74

$modelname "v_models/anim_v_HuntingRifle.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition -2.408 -19.536 -12.255

$cdmaterials "models\v_models\"

$attachment "fowardnode" "ValveBiped.weapon_bone" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -1.925 -12.35 -21.539 40.998 7.534 -2.972

$definebone "ValveBiped.Bip01_Spine2" "" 3.698241 0 0 0 -0.906992 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_Spine4" "ValveBiped.Bip01_Spine2" 5.70089 0 0 0 28.371668 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Clavicle" "ValveBiped.Bip01_Spine4" 4.065391 1.458947 1.5 -63.87528 -147.035805 50.277504 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_UpperArm" "ValveBiped.Bip01_L_Clavicle" 5.50736 -0.000003 0 -19.730431 -44.165482 -79.348295 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Forearm" "ValveBiped.Bip01_L_UpperArm" 10.9074 0 0.000001 -0.000003 -7.20248 -0.000002 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Hand" "ValveBiped.Bip01_L_Forearm" 10.424325 -0.000007 -0.000031 6.507306 7.122669 78.669798 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger4" "ValveBiped.Bip01_L_Hand" 2.997272 0.005408 -1.477473 8.213353 -12.990152 11.742422 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger41" "ValveBiped.Bip01_L_Finger4" 1.510382 0.000001 0 0.955243 -34.37459 0.653402 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger42" "ValveBiped.Bip01_L_Finger41" 0.808655 0 0 -10.048532 -17.354256 -3.121074 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger3" "ValveBiped.Bip01_L_Hand" 3.30579 0.203112 -0.54673 5.954123 -16.778204 11.337856 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger31" "ValveBiped.Bip01_L_Finger3" 1.807177 0 0 -5.063455 -30.512975 -2.9776 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger32" "ValveBiped.Bip01_L_Finger31" 0.966144 0.000002 0 0.559038 -13.904476 0.138371 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger2" "ValveBiped.Bip01_L_Hand" 3.57151 0.109303 0.40958 3.893596 -14.791073 10.730292 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger21" "ValveBiped.Bip01_L_Finger2" 2.150655 0.000002 0 -3.092652 -37.967154 -2.410834 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger22" "ValveBiped.Bip01_L_Finger21" 1.152752 0.000002 0 0.688641 -8.970338 0.10869 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger1" "ValveBiped.Bip01_L_Hand" 3.684093 -0.158702 1.419182 1.961121 -11.693717 10.352716 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger11" "ValveBiped.Bip01_L_Finger1" 1.701013 -0.000001 0 3.669056 -38.756252 2.940822 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger12" "ValveBiped.Bip01_L_Finger11" 0.99471 0.000002 0 2.209331 -1.896546 0.073169 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger0" "ValveBiped.Bip01_L_Hand" 1.068072 -1.287203 0.981903 -19.741842 -7.111207 97.051428 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger01" "ValveBiped.Bip01_L_Finger0" 1.836304 0 0 -10.778416 -10.615987 0.000001 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger02" "ValveBiped.Bip01_L_Finger01" 1.223946 0 -0.000003 -2.328836 11.249065 0.000002 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Ulna" "ValveBiped.Bip01_L_Forearm" 5.212174 0 0 -0.000003 0 -5.467968 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Wrist" "ValveBiped.Bip01_L_Forearm" 10.42435 0 0 -0.000003 0 -10.363949 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Clavicle" "ValveBiped.Bip01_Spine4" 4.065391 1.458947 -1.5 63.87528 -147.035805 -54.583283 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_UpperArm" "ValveBiped.Bip01_R_Clavicle" 5.50736 0 -0.000001 22.698467 -42.953728 82.694999 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Forearm" "ValveBiped.Bip01_R_UpperArm" 10.907396 0 -0.000002 0.000003 -7.202477 0.000002 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Hand" "ValveBiped.Bip01_R_Forearm" 10.424301 -0.000004 0.000014 -6.507536 7.122612 -78.876985 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger4" "ValveBiped.Bip01_R_Hand" 2.997293 0.000065 1.477481 -8.213407 -12.989927 -11.535191 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger41" "ValveBiped.Bip01_R_Finger4" 1.510386 -0.000001 0 -0.955233 -34.374607 -0.653401 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger42" "ValveBiped.Bip01_R_Finger41" 0.808651 0 0 10.048538 -17.354271 3.121072 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger3" "ValveBiped.Bip01_R_Hand" 3.30581 0.201132 0.547461 -5.954235 -16.777986 -11.130628 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger31" "ValveBiped.Bip01_R_Finger3" 1.807175 0 0 5.063457 -30.512989 2.977604 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger32" "ValveBiped.Bip01_R_Finger31" 0.96614 0 0 -0.559038 -13.904483 -0.138368 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger2" "ValveBiped.Bip01_R_Hand" 3.571527 0.110783 -0.409181 -3.893706 -14.790908 -10.523119 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger21" "ValveBiped.Bip01_R_Finger2" 2.150659 -0.000002 0 3.092654 -37.967167 2.410835 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger22" "ValveBiped.Bip01_R_Finger21" 1.152751 0.000002 0 -0.688638 -8.970339 -0.108689 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger1" "ValveBiped.Bip01_R_Hand" 3.684117 -0.153568 -1.419746 -1.961177 -11.693496 -10.145484 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger11" "ValveBiped.Bip01_R_Finger1" 1.701015 0.000001 0 -3.669047 -38.756245 -2.940821 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger12" "ValveBiped.Bip01_R_Finger11" 0.994707 0.000002 0 -2.209319 -1.896548 -0.073166 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger0" "ValveBiped.Bip01_R_Hand" 1.068095 -1.283653 -0.986553 19.767268 -7.037123 -96.832985 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger01" "ValveBiped.Bip01_R_Finger0" 1.836304 -0.000001 0.000001 10.778428 -10.615994 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger02" "ValveBiped.Bip01_R_Finger01" 1.223944 0 0 2.328847 11.249042 -0.000001 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Ulna" "ValveBiped.Bip01_R_Forearm" 5.212174 0.000001 0 0.000003 0.000003 5.367815 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Wrist" "ValveBiped.Bip01_R_Forearm" 10.424347 0 -0.000001 0.000003 0.000003 10.169717 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone" "ValveBiped.Bip01_Spine2" 0 0.744264 2.049373 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_trigger" "ValveBiped.weapon_bone" 0.016468 1.493589 4.320832 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_Clip" "ValveBiped.weapon_bone" -0.015713 1.212083 8.042111 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_misc01" "ValveBiped.weapon_bone" 0.016468 2.164163 19.591322 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_safety" "ValveBiped.weapon_bone" 0.152936 1.951204 5.544861 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_misc02" "ValveBiped.weapon_bone" -0.004418 3.600822 8.838447 0 0 0 0 0 0 0 0 0
$definebone "ValveBiped.weapon_bone_forwardassist" "ValveBiped.weapon_bone" -0.54251 3.306289 9.852657 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32 nostall

$bonesaveframe "ValveBiped.Bip01_Spine2" position rotation
$bonesaveframe "ValveBiped.Bip01_Spine4" rotation
$bonesaveframe "ValveBiped.Bip01_L_Clavicle" rotation
$bonesaveframe "ValveBiped.Bip01_L_UpperArm" rotation
$bonesaveframe "ValveBiped.Bip01_L_Forearm" rotation
$bonesaveframe "ValveBiped.Bip01_L_Hand" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger4" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger41" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger42" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger3" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger31" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger32" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger2" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger21" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger22" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger1" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger11" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger12" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger0" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger01" rotation
$bonesaveframe "ValveBiped.Bip01_L_Finger02" rotation
$bonesaveframe "ValveBiped.Bip01_L_Ulna" rotation
$bonesaveframe "ValveBiped.Bip01_L_Wrist" rotation
$bonesaveframe "ValveBiped.Bip01_R_Clavicle" rotation
$bonesaveframe "ValveBiped.Bip01_R_UpperArm" rotation
$bonesaveframe "ValveBiped.Bip01_R_Forearm" rotation
$bonesaveframe "ValveBiped.Bip01_R_Hand" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger4" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger41" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger42" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger3" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger31" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger32" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger2" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger21" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger22" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger1" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger11" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger12" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger0" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger01" rotation
$bonesaveframe "ValveBiped.Bip01_R_Finger02" rotation
$bonesaveframe "ValveBiped.Bip01_R_Ulna" rotation
$bonesaveframe "ValveBiped.Bip01_R_Wrist" rotation
$bonesaveframe "ValveBiped.weapon_bone" position rotation
$bonesaveframe "ValveBiped.weapon_bone_trigger" rotation
$bonesaveframe "ValveBiped.weapon_bone_Clip" position rotation
$bonesaveframe "ValveBiped.weapon_bone_misc01" rotation
$bonesaveframe "ValveBiped.weapon_bone_safety" rotation
$bonesaveframe "ValveBiped.weapon_bone_misc02" rotation
$bonesaveframe "ValveBiped.weapon_bone_forwardassist" position rotation

$sectionframes 30 120

$poseparameter "ver_aims" -1 1 loop 0
$poseparameter "move_x" -1 1 loop 0

$ikchain "rhand" "ValveBiped.Bip01_R_Hand" knee 0.707 0.707 0
$ikchain "lhand" "ValveBiped.Bip01_L_Hand" knee 0.707 0.707 0

$animation "a_sniper_arms_trans_down_corrective_animation" "anim_v_huntingrifle_anims\a_sniper_arms_trans_down_corrective_animation.smd" {
}

$animation "a_sniper_arms_trans_corrective_animation" "anim_v_huntingrifle_anims\a_sniper_arms_trans_corrective_animation.smd" {
}

$animation "a_sniper_arms_trans_up_corrective_animation" "anim_v_huntingrifle_anims\a_sniper_arms_trans_up_corrective_animation.smd" {
}

$animation "anim_Sniper_pickup_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_pickup_corrective_animation.smd" {
}

$animation "anim_Sniper_pickup_partial_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_pickup_partial_corrective_animation.smd" {
}

$animation "anim_Sniper_pickup_partial2_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_pickup_partial2_corrective_animation.smd" {
}

$animation "anim_Sniper_reload_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_reload_corrective_animation.smd" {
}

$animation "anim_Sniper_reload_clipout_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_reload_clipout_corrective_animation.smd" {
}

$animation "anim_Sniper_reload_empty_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_reload_empty_corrective_animation.smd" {
}

$animation "anim_Sniper_reload_empty_clipout_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_reload_empty_clipout_corrective_animation.smd" {
}

$animation "anim_Sniper_reload_empty_partial_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_reload_empty_partial_corrective_animation.smd" {
}

$animation "anim_Sniper_deploy_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_deploy_corrective_animation.smd" {
}

$animation "anim_Sniper_shoot_corrective_animation" "anim_v_huntingrifle_anims\anim_Sniper_shoot_corrective_animation.smd" {
}

$animation "anim_Sniper_neutral" "anim_v_huntingrifle_anims\anim_Sniper_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
}

$animation "a_sniper_pose_neutral" "anim_v_huntingrifle_anims\a_sniper_pose_neutral.smd" {
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 0 0 target 1
}

$animation "a_sniper_arms_trans_down" "anim_v_huntingrifle_anims\a_sniper_arms_trans_down.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sniper_arms_trans_down_corrective_animation" 0
}

$animation "a_sniper_arms_trans" "anim_v_huntingrifle_anims\a_sniper_arms_trans.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sniper_arms_trans_corrective_animation" 0
}

$animation "a_sniper_arms_trans_up" "anim_v_huntingrifle_anims\a_sniper_arms_trans_up.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "a_sniper_arms_trans_up_corrective_animation" 0
}

$animation "ta_sniper_run_trans_idle" "anim_v_huntingrifle_anims\ta_sniper_run_trans_idle.smd" {
	fps 30
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 80 80 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 80 80 target 0
}

$animation "ta_sniper_run_trans_run" "anim_v_huntingrifle_anims\ta_sniper_run_trans_run.smd" {
	fps 30
	loop
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
}

$animation "anim_Sniper_pickup" "anim_v_huntingrifle_anims\anim_Sniper_pickup.smd" {
	fps 32
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_pickup_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 145 145 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 145 145 target 0
}

$animation "anim_Sniper_pickup_partial" "anim_v_huntingrifle_anims\anim_Sniper_pickup_partial.smd" {
	fps 32
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_pickup_partial_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 105 105 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 105 105 target 0
}

$animation "anim_Sniper_pickup_partial2" "anim_v_huntingrifle_anims\anim_Sniper_pickup_partial2.smd" {
	fps 32
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_pickup_partial2_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
}

$animation "anim_Sniper_reload" "anim_v_huntingrifle_anims\anim_Sniper_reload.smd" {
	fps 32
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_reload_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 120 120 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 120 120 target 0
}

$animation "anim_Sniper_reload_clipout" "anim_v_huntingrifle_anims\anim_Sniper_reload_clipout.smd" {
	fps 32
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_reload_clipout_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 80 80 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 80 80 target 0
}

$animation "anim_Sniper_reload_empty" "anim_v_huntingrifle_anims\anim_Sniper_reload_empty.smd" {
	fps 32
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_reload_empty_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 130 130 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 130 130 target 0
}

$animation "anim_Sniper_reload_empty_clipout" "anim_v_huntingrifle_anims\anim_Sniper_reload_empty_clipout.smd" {
	fps 32
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_reload_empty_clipout_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 90 90 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 90 90 target 0
}

$animation "anim_Sniper_reload_empty_partial" "anim_v_huntingrifle_anims\anim_Sniper_reload_empty_partial.smd" {
	fps 32
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_reload_empty_partial_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 45 45 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 45 45 target 0
}

$animation "anim_Sniper_deploy" "anim_v_huntingrifle_anims\anim_Sniper_deploy.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_deploy_corrective_animation" 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 55 55 target 0
}

$animation "anim_Sniper_shoot" "anim_v_huntingrifle_anims\anim_Sniper_shoot.smd" {
	fps 30
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "anim_Sniper_shoot_corrective_animation" 0
}

$sequence "a_sniper_arms_vaims" {
	"a_sniper_arms_trans_down"
	"a_sniper_arms_trans"
	"a_sniper_arms_trans_up"
	blend "ver_aims" 1 -1
	blendwidth 3
	delta
	fadein 0.2
	fadeout 0.2
	hidden
}

$sequence "sniper_idle" {
	"ta_sniper_run_trans_run"
	"ta_sniper_run_trans_idle"
	"ta_sniper_run_trans_run"
	activity "ACT_VM_IDLE_SNIPER" 1
	blend "move_x" 1 -1
	blendwidth 3
	fadein 0.2
	fadeout 0.2
	addlayer "a_sniper_arms_vaims"
}

$sequence "sniper_pickup" {
	"anim_v_huntingrifle_anims\sniper_pickup.smd"
	activity "ACT_VM_PICKUP_SNIPER" 1
	{ event AE_PICKUP_CLIPIN 40 "" }
	fadein 0.2
	fadeout 0.2
	fps 32
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 131 131 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 131 131 target 1
}

$sequence "Sniper_pickup_layer" {
	"anim_Sniper_pickup"
	activity "ACT_VM_PICKUP_SNIPER_LAYER" 1
	delta
	{ event 5004 20 "HuntingRifle.ClipIn" }
	{ event 5004 38 "HuntingRifle.ClipLocked" }
	{ event 5004 71 "HuntingRifle.BoltBack" }
	{ event 5004 82 "HuntingRifle.BoltForward" }
	{ event 5004 115 "HuntingRifle.PushButton" }
	{ event AE_PICKUP_CLIPIN 40 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "sniper_pickup_partial" {
	"anim_v_huntingrifle_anims\sniper_pickup_partial.smd"
	activity "ACT_VM_PICKUP_CLIPIN_SNIPER" 1
	{ event AE_PICKUP_CHARGING 40 "" }
	fadein 0.2
	fadeout 0.2
	fps 32
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 93 93 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 93 93 target 1
}

$sequence "Sniper_pickup_partial_layer" {
	"anim_Sniper_pickup_partial"
	activity "ACT_VM_PICKUP_CLIPIN_SNIPER_LAYER" 1
	delta
	{ event 5004 31 "HuntingRifle.BoltBack" }
	{ event 5004 42 "HuntingRifle.BoltForward" }
	{ event 5004 75 "HuntingRifle.PushButton" }
	{ event AE_PICKUP_CHARGING 40 "" }
	fadein 0
	fadeout 0.2
}

$sequence "sniper_pickup_partial2" {
	"anim_v_huntingrifle_anims\sniper_pickup_partial2.smd"
	activity "ACT_VM_PICKUP_CHARGING_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	fps 32
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 38 38 target 1
}

$sequence "Sniper_pickup_partial2_layer" {
	"anim_Sniper_pickup_partial2"
	activity "ACT_VM_PICKUP_CHARGING_SNIPER_LAYER" 1
	delta
	{ event 5004 20 "HuntingRifle.PushButton" }
	fadein 0
	fadeout 0.2
}

$sequence "sniper_reload1" {
	"anim_v_huntingrifle_anims\sniper_reload1.smd"
	activity "ACT_VM_RELOAD_SNIPER" 1
	{ event AE_RELOAD_CLIPOUT 27 "" }
	fadein 0.2
	fadeout 0.2
	fps 32
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 100 100 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 100 100 target 1
}

$sequence "Sniper_reload_layer" {
	"anim_Sniper_reload"
	activity "ACT_VM_RELOAD_SNIPER_LAYER" 1
	delta
	{ event 5004 18 "HuntingRifle.ClipOut" }
	{ event 5004 61 "HuntingRifle.ClipIn" }
	{ event 5004 80 "HuntingRifle.ClipLocked" }
	{ event AE_RELOAD_CLIPOUT 27 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "sniper_reload_clipout" {
	"anim_v_huntingrifle_anims\sniper_reload_clipout.smd"
	activity "ACT_VM_RELOAD_CLIPOUT_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	fps 32
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "Sniper_reload_clipout_layer" {
	"anim_Sniper_reload_clipout"
	activity "ACT_VM_RELOAD_CLIPOUT_SNIPER_LAYER" 1
	delta
	{ event 5004 21 "HuntingRifle.ClipIn" }
	{ event 5004 38 "HuntingRifle.ClipLocked" }
	fadein 0.2
	fadeout 0.2
}

$sequence "sniper_reload_empty" {
	"anim_v_huntingrifle_anims\sniper_reload_empty.smd"
	activity "ACT_VM_RELOAD_EMPTY_SNIPER" 1
	{ event AE_RELOAD_EMPTY_CLIPOUT 27 "" }
	{ event AE_RELOAD_EMPTY_CLIPIN 80 "" }
	fadein 0.2
	fadeout 0.2
	fps 32
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 121 121 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 121 121 target 1
}

$sequence "Sniper_reload_empty_layer" {
	"anim_Sniper_reload_empty"
	activity "ACT_VM_RELOAD_EMPTY_SNIPER_LAYER" 1
	delta
	{ event 5004 19 "HuntingRifle.ClipOut" }
	{ event 5004 61 "HuntingRifle.ClipIn" }
	{ event 5004 78 "HuntingRifle.ClipLocked" }
	{ event 5004 107 "HuntingRifle.PushButton" }
	{ event AE_RELOAD_EMPTY_CLIPOUT 27 "" }
	{ event AE_RELOAD_EMPTY_CLIPIN 80 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "sniper_reload_empty_clipout" {
	"anim_v_huntingrifle_anims\sniper_reload_empty_clipout.smd"
	activity "ACT_VM_RELOAD_EMPTY_CLIPOUT_SNIPER" 1
	{ event AE_RELOAD_EMPTY_CLIPIN 40 "" }
	fadein 0.2
	fadeout 0.2
	fps 32
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 81 81 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 81 81 target 1
}

$sequence "Sniper_reload_empty_clipout_layer" {
	"anim_Sniper_reload_empty_clipout"
	activity "ACT_VM_RELOAD_EMPTY_CLIPOUT_SNIPER_LAYER" 1
	delta
	{ event 5004 20 "HuntingRifle.ClipIn" }
	{ event 5004 39 "HuntingRifle.ClipLocked" }
	{ event 5004 67 "HuntingRifle.PushButton" }
	{ event AE_RELOAD_EMPTY_CLIPIN 40 "" }
	fadein 0.2
	fadeout 0.2
}

$sequence "sniper_reload_empty_partial" {
	"anim_v_huntingrifle_anims\sniper_reload_empty_partial.smd"
	activity "ACT_VM_RELOAD_EMPTY_CLIPIN_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	fps 32
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 45 45 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 45 45 target 1
}

$sequence "Sniper_reload_empty_partial_layer" {
	"anim_Sniper_reload_empty_partial"
	activity "ACT_VM_RELOAD_EMPTY_CLIPIN_SNIPER_LAYER" 1
	delta
	{ event 5004 20 "HuntingRifle.PushButton" }
	fadein 0
	fadeout 0.2
}

$sequence "sniper_draw" {
	"anim_v_huntingrifle_anims\sniper_draw.smd"
	activity "ACT_VM_DEPLOY_SNIPER" 1
	{ event 5004 13 "HuntingRifle.Deploy" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "Sniper_deploy_layer" {
	"anim_Sniper_deploy"
	activity "ACT_VM_DEPLOY_SNIPER_LAYER" 1
	delta
	{ event 5004 1 "HuntingRifle.Deploy" }
	fadein 0
	fadeout 0.2
}

$sequence "sniper_shoot1" {
	"anim_v_huntingrifle_anims\sniper_shoot1.smd"
	activity "ACT_VM_PRIMARYATTACK_SNIPER" 1
	{ event AE_MUZZLEFLASH 0 "1" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
}

$sequence "Sniper_shoot_layer" {
	"anim_Sniper_shoot"
	activity "ACT_VM_SHOOT_SNIPER_LAYER" 1
	delta
	{ event AE_CL_CREATE_PARTICLE_BRASS 2 "weapon_shell_casing_rifle" }
	{ event AE_MUZZLEFLASH 0 "1" }
	fadein 0.1
	fadeout 0.2
}

$sequence "sniper_melee" {
	"anim_v_huntingrifle_anims\sniper_melee.smd"
	activity "ACT_VM_MELEE_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 40
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 35 35 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 35 35 target 1
}

$sequence "Sniper_melee_layer" {
	"anim_v_huntingrifle_anims\Sniper_melee_layer.smd"
	activity "ACT_VM_MELEE_SNIPER_LAYER" 1
	fadein 0
	fadeout 0.2
	fps 40
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 35 35 target 1
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 35 35 target 0
}

$sequence "sniper_ItemPickup_idle" {
	"anim_v_huntingrifle_anims\sniper_ItemPickup_idle.smd"
	activity "ACT_VM_ITEMPICKUP_LOOP_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "sniper_ItemPickup_idle_layer" {
	"anim_v_huntingrifle_anims\sniper_ItemPickup_idle_layer.smd"
	activity "ACT_VM_ITEMPICKUP_LOOP_SNIPER_LAYER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "sniper_ItemPickup_extend" {
	"anim_v_huntingrifle_anims\sniper_ItemPickup_extend.smd"
	activity "ACT_VM_ITEMPICKUP_EXTEND_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "sniper_ItemPickup_extend_layer" {
	"anim_v_huntingrifle_anims\sniper_ItemPickup_extend_layer.smd"
	activity "ACT_VM_ITEMPICKUP_EXTEND_SNIPER_LAYER" 1
	{ event 5004 1 "HuntingRifle.ItemPickupExtend" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
}

$sequence "sniper_ItemPickup_retract" {
	"anim_v_huntingrifle_anims\sniper_ItemPickup_retract.smd"
	activity "ACT_VM_ITEMPICKUP_RETRACT_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "sniper_ItemPickup_retract_layer" {
	"anim_v_huntingrifle_anims\sniper_ItemPickup_retract_layer.smd"
	activity "ACT_VM_ITEMPICKUP_RETRACT_SNIPER_LAYER" 1
	{ event 5004 1 "HuntingRifle.ItemPickupRetract" }
	fadein 0
	fadeout 0.4
	fps 80
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
}

$sequence "sniper_HelpingHand_idle" {
	"anim_v_huntingrifle_anims\sniper_HelpingHand_idle.smd"
	activity "ACT_VM_HELPINGHAND_LOOP_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "sniper_HelpingHand_idle_layer" {
	"anim_v_huntingrifle_anims\sniper_HelpingHand_idle_layer.smd"
	activity "ACT_VM_HELPINGHAND_LOOP_SNIPER_LAYER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "sniper_HelpingHand_extend" {
	"anim_v_huntingrifle_anims\sniper_HelpingHand_extend.smd"
	activity "ACT_VM_HELPINGHAND_EXTEND_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "sniper_HelpingHand_extend_layer" {
	"anim_v_huntingrifle_anims\sniper_HelpingHand_extend_layer.smd"
	activity "ACT_VM_HELPINGHAND_EXTEND_SNIPER_LAYER" 1
	{ event 5004 1 "HuntingRifle.HelpingHandExtend" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 60 60 target 1
}

$sequence "sniper_HelpingHand_retract" {
	"anim_v_huntingrifle_anims\sniper_HelpingHand_retract.smd"
	activity "ACT_VM_HELPINGHAND_RETRACT_SNIPER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 80
	ikrule "rhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 0
	ikrule "lhand" release contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 30 30 target 1
}

$sequence "sniper_HelpingHand_retract_layer" {
	"anim_v_huntingrifle_anims\sniper_HelpingHand_retract_layer.smd"
	activity "ACT_VM_HELPINGHAND_RETRACT_SNIPER_LAYER" 1
	{ event 5004 1 "HuntingRifle.HelpingHandRetract" }
	fadein 0
	fadeout 0.4
	fps 80
	ikrule "rhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 0
	ikrule "lhand" touch "ValveBiped.weapon_bone" contact 0 fakeorigin 0 0 0 fakerotate 0 0 0 floor 0 height 0 radius 0 range 0 0 50 50 target 1
}
