// Created by Crowbar 0.74

$modelname "swarm\Shieldbug\Shieldbug.mdl"

$bodygroup "Shieldbug"
{
	studio "ShieldbugRef.smd"
}


$surfaceprop "alienflesh"

$contents "solid"

$illumposition -0.289 58.958 50.569

$eyeposition 0 0 20

$cdmaterials "swarm\models\Shieldbug\"

$cbox 0 0 0 0 0 0

$bbox -179.662 -83.014 -14.75 61.746 82.436 115.889

$definebone "Bone02" "" -0.000002 -43.353905 -25.380503 -63.434965 89.999982 -89.999982 0 0 0 0 0 0
$definebone "Bone23" "Bone02" 26.428173 -0.000002 0.000002 -7.431033 154.456873 -7.852673 0 0 0 0 0 0
$definebone "Bone24" "Bone23" 40.133087 -0.000004 0 -78.702569 -48.739916 15.219535 0 0 0 0 0 0
$definebone "Bone25" "Bone24" 17.693981 -0.000003 -0.000001 -12.181713 -2.711122 35.611906 0 0 0 0 0 0
$definebone "Bone26" "Bone25" 38.630093 0.000013 0.000005 75.105313 9.060632 7.550333 0 0 0 0 0 0
$definebone "Bone23(mirrored)" "Bone02" 26.428177 -0.000002 -0.386392 7.430995 154.45686 -172.147282 0 0 0 0 0 0
$definebone "Bone24(mirrored)" "Bone23(mirrored)" 40.133087 0.000015 -0.000007 -78.702569 48.739977 -15.219533 0 0 0 0 0 0
$definebone "Bone25(mirrored)" "Bone24(mirrored)" 17.693991 0.00001 0 -12.183661 2.708545 -35.607091 0 0 0 0 0 0
$definebone "Bone26(mirrored)" "Bone25(mirrored)" 38.630093 -0.000003 -0.000019 75.105368 -9.060571 -7.550274 0 0 0 0 0 0
$definebone "Bone14" "Bone02" 25.891573 4.441158 20.706804 -24.505576 123.284819 40.458554 0 0 0 0 0 0
$definebone "Bone15" "Bone14" 26.48564 0.000002 -0.000004 -8.904165 -89.329968 34.116484 0 0 0 0 0 0
$definebone "Bone16" "Bone15" 34.730843 0.000007 -0.000001 43.243024 85.343323 -26.824569 0 0 0 0 0 0
$definebone "Bone14(mirrored)" "Bone02" 25.891565 4.441155 -21.093197 24.505554 123.284737 139.541448 0 0 0 0 0 0
$definebone "Bone15(mirrored)" "Bone14(mirrored)" 26.485632 -0.000011 0.000004 -8.904221 89.329968 -34.116488 0 0 0 0 0 0
$definebone "Bone16(mirrored)" "Bone15(mirrored)" 34.730839 0.000005 -0.000002 43.24302 -85.343323 26.824567 0 0 0 0 0 0
$definebone "Bone03" "Bone02" 0.000001 0.000004 0 0 -139.028268 0 0 0 0 0 0 0
$definebone "Bone04" "Bone03" 23.335119 -0.000002 0 0 16.172537 0 0 0 0 0 0 0
$definebone "Bone05" "Bone04" 26.49316 0 0 0.170054 6.290676 0 0 0 0 0 0 0
$definebone "Bone06" "Bone05" 40.640911 0.000001 0 0 0 0 0 0 0 0 0 0
$definebone "Bone07" "Bone06" 23.638077 0.000005 0 0 0.987722 0 0 0 0 0 0 0
$definebone "Bone18" "Bone02" 0.000001 0.000004 0.000002 -7.53176 143.633756 -6.641211 0 0 0 0 0 0
$definebone "Bone19" "Bone18" 15.859938 -0.000008 0 -64.7051 77.005294 -39.400073 0 0 0 0 0 0
$definebone "Bone20" "Bone19" 22.877913 0.000007 0.000002 -15.308172 11.737613 -25.740411 0 0 0 0 0 0
$definebone "Bone21" "Bone20" 40.219398 -0.000001 0.000009 73.183442 -5.271391 -4.599643 0 0 0 0 0 0
$definebone "Bone18(mirrored)" "Bone02" 0.000006 0.000005 -0.386392 7.531741 143.633742 -173.358794 0 0 0 0 0 0
$definebone "Bone19(mirrored)" "Bone18(mirrored)" 15.859936 0.000004 0.000009 -64.7051 -77.005363 39.400131 0 0 0 0 0 0
$definebone "Bone20(mirrored)" "Bone19(mirrored)" 22.877901 -0.000007 0.000001 -15.303643 -11.746669 25.756228 0 0 0 0 0 0
$definebone "Bone21(mirrored)" "Bone20(mirrored)" 40.219391 0.000008 -0.000007 73.183442 5.271541 4.59977 0 0 0 0 0 0
$definebone "Bone01" "Bone02" 26.428171 -0.000003 0.000003 0 37.610611 0 0 0 0 0 0 0
$definebone "connectBone01" "Bone01" 16.506283 -0.000003 -0.000003 0 -9.439881 0 0 0 0 0 0 0
$definebone "Bone10" "connectBone01" 8.750626 -0.000001 -0.000001 0 15.484643 0 0 0 0 0 0 0
$definebone "Bone12" "connectBone01" 8.750672 -0.000061 -0.000001 0.000057 66.235295 0 0 0 0 0 0 0
$definebone "Bone13" "Bone12" 27.0306 0.00001 0.000005 0 0 0 0 0 0 0 0 0


$poseparameter "move_yaw" -180 180 loop 0
$poseparameter "move_defend" 0 100 loop 0

$sequence "Idle01" {
	"shieldbug_anims\Idle01.smd"
	activity "ACT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Idle02" {
	"shieldbug_anims\Idle02.smd"
	activity "ACT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Idle03" {
	"shieldbug_anims\Idle03.smd"
	activity "ACT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Idle04" {
	"shieldbug_anims\Idle04.smd"
	activity "ACT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Idle05" {
	"shieldbug_anims\Idle05.smd"
	activity "ACT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ForwardGallop" {
	"shieldbug_anims\ForwardGallop.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "ForwardRun" {
	"shieldbug_anims\ForwardRun.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "ForwardNormal" {
	"shieldbug_anims\ForwardNormal.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "ForwardDefend" {
	"shieldbug_anims\ForwardDefend.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "ForwardDefendRun" {
	"shieldbug_anims\ForwardDefendRun.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "BackNormal" {
	"shieldbug_anims\BackNormal.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "BackDefend" {
	"shieldbug_anims\BackDefend.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "RightNormal" {
	"shieldbug_anims\RightNormal.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "RightDefend" {
	"shieldbug_anims\RightDefend.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "LeftNormal" {
	"shieldbug_anims\LeftNormal.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "LeftDefend" {
	"shieldbug_anims\LeftDefend.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
	walkframe 32 LX LY
}

$sequence "Run_All" {
	"shieldbug_anims\Run_All.smd"
	"shieldbug_anims\Run_All_2.smd"
	"shieldbug_anims\Run_All_3.smd"
	"shieldbug_anims\Run_All_4.smd"
	"shieldbug_anims\Run_All_5.smd"
	"shieldbug_anims\Run_All_6.smd"
	"shieldbug_anims\Run_All_7.smd"
	"shieldbug_anims\Run_All_8.smd"
	"shieldbug_anims\Run_All_9.smd"
	"shieldbug_anims\Run_All_10.smd"
	activity "ACT_RUN" 1
	blend "move_yaw" -180 180
	blend "move_defend" 0 100
	blendwidth 5
	{ event AE_MARINE_FOOTSTEP 16 "" }
	{ event AE_MARINE_FOOTSTEP 32 "" }
	{ event AE_MARINE_FOOTSTEP 3 "" }
	{ event AE_MARINE_FOOTSTEP 19 "" }
	{ event AE_MARINE_FOOTSTEP 13 "" }
	{ event AE_MARINE_FOOTSTEP 29 "" }
	{ event AE_SHIELDBUG_SCREENSHAKE 8 "" }
	{ event AE_SHIELDBUG_SCREENSHAKE 23 "" }
	fadein 0.2
	fadeout 0.2
	node "running"
	fps 30
	loop
	walkframe 32 LX LY
}

$sequence "Turn_Right" {
	"shieldbug_anims\Turn_Right.smd"
	"shieldbug_anims\Turn_Right_2.smd"
	activity "ACT_TURN_RIGHT" 1
	blend "move_defend" 0 100
	blendwidth 2
	fadein 0.2
	fadeout 0.2
	node "standing"
	fps 14.2222
	loop
}

$sequence "Turn_Left" {
	"shieldbug_anims\Turn_Left.smd"
	"shieldbug_anims\Turn_Left_2.smd"
	activity "ACT_TURN_LEFT" 1
	blend "move_defend" 0 100
	blendwidth 2
	fadein 0.2
	fadeout 0.2
	node "standing"
	fps 14.2222
	loop
}

$sequence "attack_clobber" {
	"shieldbug_anims\attack_clobber.smd"
	activity "ACT_MELEE_ATTACK1" 1
	{ event AE_SHIELDBUG_MELEE1_SOUND 19 "" }
	{ event AE_SHIELDBUG_MELEE_HIT1 19 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "attack_swipe" {
	"shieldbug_anims\attack_swipe.smd"
	activity "ACT_MELEE_ATTACK1" 1
	{ event AE_SHIELDBUG_MELEE1_SOUND 19 "" }
	{ event AE_SHIELDBUG_MELEE_HIT1 19 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "attack_backhand" {
	"shieldbug_anims\attack_backhand.smd"
	{ event AE_SHIELDBUG_MELEE1_SOUND 10 "" }
	{ event AE_SHIELDBUG_MELEE_HIT1 12 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "throw_crate" {
	"shieldbug_anims\throw_crate.smd"
	{ event AE_SHIELDBUG_MELEE1_SOUND 23 "" }
	{ event 1003 23 "1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "throw_crate2" {
	"shieldbug_anims\throw_crate2.smd"
	{ event AE_SHIELDBUG_MELEE1_SOUND 23 "" }
	{ event 1003 23 "1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "throw_crate3" {
	"shieldbug_anims\throw_crate3.smd"
	{ event AE_SHIELDBUG_MELEE1_SOUND 23 "" }
	{ event 1003 23 "1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "flinch_left" {
	"shieldbug_anims\flinch_left.smd"
	activity "ACT_FLINCH_LEFTARM" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "flinch_right" {
	"shieldbug_anims\flinch_right.smd"
	activity "ACT_FLINCH_RIGHTARM" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ShoverRoar" {
	"shieldbug_anims\ShoverRoar.smd"
	activity "ACT_ALIEN_SHOVER_ROAR" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Shove" {
	"shieldbug_anims\Shove.smd"
	activity "ACT_ALIEN_SHOVER_SHOVE_PHYSOBJECT" 1
	{ event AE_SHIELDBUG_MELEE1_SOUND 19 "" }
	{ event AE_ALIEN_SHOVER_SHOVE_PHYSOBJECT 19 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "leap_pre" {
	"shieldbug_anims\leap_pre.smd"
	activity "ACT_SHIELDBUG_PRE_LEAP" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "headhit" {
	"shieldbug_anims\headhit.smd"
	activity "ACT_MELEE_ATTACK2" 1
	{ event AE_SHIELDBUG_MELEE1_SOUND 20 "" }
	{ event AE_SHIELDBUG_MELEE_HIT1 25 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
	walkframe 24 LX LY
}

$sequence "leap" {
	"shieldbug_anims\leap.smd"
	{ event AE_SHIELDBUG_MELEE1_SOUND 20 "" }
	{ event AE_SHIELDBUG_MELEE_HIT1 25 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
	walkframe 18 LX LY
	walkframe 26 LX LY
}

$sequence "ragdoll" {
	"shieldbug_anims\ragdoll.smd"
	activity "ACT_DIERAGDOLL" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$collisionjoints "shieldbug_physics.smd"
{
	$mass 200
	$inertia 10
	$damping 0.01
	$rotdamping 1.5
	$rootbone "bone02"


	$jointconstrain "Bone20(mirrored)" x limit -26 35 0
	$jointconstrain "Bone20(mirrored)" y limit -50 35 0
	$jointconstrain "Bone20(mirrored)" z limit -46 23 0

	$jointconstrain "Bone21(mirrored)" x limit -15 15 0
	$jointconstrain "Bone21(mirrored)" y limit -28 73 0
	$jointconstrain "Bone21(mirrored)" z limit -8 8 0

	$jointconstrain "Bone20" x limit -26 35 0
	$jointconstrain "Bone20" y limit -50 35 0
	$jointconstrain "Bone20" z limit -46 23 0

	$jointconstrain "Bone21" x limit -15 15 0
	$jointconstrain "Bone21" y limit -28 73 0
	$jointconstrain "Bone21" z limit -8 8 0

	$jointconstrain "Bone03" x limit -6 6 0
	$jointconstrain "Bone03" y limit -28 28 0
	$jointconstrain "Bone03" z limit -12 12 0

	$jointconstrain "Bone05" x limit 1 1 0
	$jointconstrain "Bone05" y limit -8 6 0
	$jointconstrain "Bone05" z limit -28 32 0

	$jointconstrain "Bone06" x limit -1 1 0
	$jointconstrain "Bone06" y limit -8 6 0
	$jointconstrain "Bone06" z limit -21 28 0

	$jointconstrain "Bone14(mirrored)" x limit -37 70 0
	$jointconstrain "Bone14(mirrored)" y limit -75 21 0
	$jointconstrain "Bone14(mirrored)" z limit -61 21 0

	$jointconstrain "Bone15(mirrored)" x limit -46 37 0
	$jointconstrain "Bone15(mirrored)" y limit -41 70 0
	$jointconstrain "Bone15(mirrored)" z limit -57 23 0

	$jointconstrain "Bone16(mirrored)" x limit -64 68 0
	$jointconstrain "Bone16(mirrored)" y limit -35 32 0
	$jointconstrain "Bone16(mirrored)" z limit -37 64 0

	$jointconstrain "Bone14" x limit -59 23 0
	$jointconstrain "Bone14" y limit -55 19 0
	$jointconstrain "Bone14" z limit -15 59 0

	$jointconstrain "Bone15" x limit -15 15 0
	$jointconstrain "Bone15" y limit -8 6 0
	$jointconstrain "Bone15" z limit -32 61 0

	$jointconstrain "Bone16" x limit -37 39 0
	$jointconstrain "Bone16" y limit -28 46 0
	$jointconstrain "Bone16" z limit -48 46 0

	$jointconstrain "Bone25(mirrored)" x limit -26 35 0
	$jointconstrain "Bone25(mirrored)" y limit -50 39 0
	$jointconstrain "Bone25(mirrored)" z limit -28 44 0

	$jointdamping "Bone26(mirrored)" 0.11
	$jointconstrain "Bone26(mirrored)" x limit -15 15 0
	$jointconstrain "Bone26(mirrored)" y limit -41 70 0
	$jointconstrain "Bone26(mirrored)" z limit -8 8 0

	$jointconstrain "Bone25" x limit -15 15 0
	$jointconstrain "Bone25" y limit -6 21 0
	$jointconstrain "Bone25" z limit -59 30 0

	$jointconstrain "Bone26" x limit -15 15 0
	$jointconstrain "Bone26" y limit -28 77 0
	$jointconstrain "Bone26" z limit -8 8 0

	$jointconstrain "connectBone01" x limit -28 28 0
	$jointconstrain "connectBone01" y limit -35 35 0
	$jointconstrain "connectBone01" z limit -48 37 0
}
