// Created by Crowbar 0.74

$modelname "props_lab/Scanner1_ScrapYard.mdl"

$bodygroup "Body"
{
	studio "Scanner1_ScrapYard_reference.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition -1425.918 -2398.177 577.115

$cdmaterials "models\props_lab\"

$attachment "Scanner1" "Scanner1_ScrapYard.Scanner1" 0 0 0 rotate 0 0 0
$attachment "Scanner2" "Scanner1_ScrapYard.Scanner2" 0 0 0 rotate 0 0 0
$attachment "Scanner3" "Scanner1_ScrapYard.Scanner3" 0 0 0 rotate 0 0 0
$attachment "Scanner4" "Scanner1_ScrapYard.Scanner4" 0 0 0 rotate 0 0 0
$attachment "Scanner5" "Scanner1_ScrapYard.Scanner5" 0 0 0 rotate 0 0 0
$attachment "Scanner6" "Scanner1_ScrapYard.Scanner6" 0 0 0 rotate 0 0 0
$attachment "Scanner7" "Scanner1_ScrapYard.Scanner7" 0 0 0 rotate 0 0 0
$attachment "Scanner8" "Scanner1_ScrapYard.Scanner8" 0 0 0 rotate 0 0 0
$attachment "Scanner9" "Scanner1_ScrapYard.Scanner9" 0 0 0 rotate 0 0 0
$attachment "Scanner10" "Scanner1_ScrapYard.Scanner10" 0 0 0 rotate 0 0 0
$attachment "Scanner11" "Scanner1_ScrapYard.Scanner11" 0 0 0 rotate 0 0 0
$attachment "Scanner12" "Scanner1_ScrapYard.Scanner12" 0 0 0 rotate 0 0 0
$attachment "Scanner13" "Scanner1_ScrapYard.Scanner13" 0 0 0 rotate 0 0 0
$attachment "Scanner14" "Scanner1_ScrapYard.Scanner14" 0 0 0 rotate 0 0 0
$attachment "Scanner15" "Scanner1_ScrapYard.Scanner15" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -4 -2855.837 -4 4800.355 4 1158.231

$definebone "Scanner1_ScrapYard.Base" "" 0 0 0 0 0 89.999982 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner1" "Scanner1_ScrapYard.Base" -2276.263916 1158.228882 4223.864258 -40.644362 0 21.194972 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner8" "Scanner1_ScrapYard.Scanner1" -318.198029 0.000081 318.197937 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner9" "Scanner1_ScrapYard.Scanner1" -424.263855 0.000153 424.264008 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner4" "Scanner1_ScrapYard.Scanner1" 318.198212 0.000128 318.19812 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner5" "Scanner1_ScrapYard.Scanner1" 424.264069 0.00012 424.263947 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner10" "Scanner1_ScrapYard.Scanner1" -106.06601 0.000192 318.198029 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner11" "Scanner1_ScrapYard.Scanner1" -212.132172 0.000016 424.263794 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner12" "Scanner1_ScrapYard.Scanner1" -0.000147 0.00007 424.263885 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner14" "Scanner1_ScrapYard.Scanner1" 106.066193 0.000131 318.197998 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner15" "Scanner1_ScrapYard.Scanner1" 212.132065 0.000066 424.263855 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner7" "Scanner1_ScrapYard.Scanner1" -212.132187 0.000066 212.131851 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner6" "Scanner1_ScrapYard.Scanner1" -106.065849 0.000128 106.065971 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner2" "Scanner1_ScrapYard.Scanner1" 106.06617 0.000125 106.066093 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner3" "Scanner1_ScrapYard.Scanner1" 212.132034 0.000116 212.131912 -0.000002 -0.000001 0 0 0 0 0 0 0
$definebone "Scanner1_ScrapYard.Scanner13" "Scanner1_ScrapYard.Scanner1" 0.000014 0.000119 212.13179 -0.000002 -0.000001 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "Scanner1_ScrapYard.Base" position rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner1" position rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner8" rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner9" rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner4" position rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner5" position rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner10" rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner11" position rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner12" position rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner14" position rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner15" position rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner7" rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner6" rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner2" rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner3" rotation
$bonesaveframe "Scanner1_ScrapYard.Scanner13" rotation

$sectionframes 30 400

$sequence "Idle" {
	"scanner1_scrapyard_anims\Idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Loop" {
	"scanner1_scrapyard_anims\Loop.smd"
	{ event 6002 10 "Scanner1 sprites/scanner" }
	{ event 6002 10 "Scanner2 sprites/scanner" }
	{ event 6002 10 "Scanner3 sprites/scanner" }
	{ event 6002 10 "Scanner4 sprites/scanner" }
	{ event 6002 10 "Scanner5 sprites/scanner" }
	{ event 6002 10 "Scanner6 sprites/scanner" }
	{ event 6002 10 "Scanner7 sprites/scanner" }
	{ event 6002 10 "Scanner8 sprites/scanner" }
	{ event 6002 10 "Scanner9 sprites/scanner" }
	{ event 6002 10 "Scanner10 sprites/scanner" }
	{ event 6002 10 "Scanner11 sprites/scanner" }
	{ event 6002 10 "Scanner12 sprites/scanner" }
	{ event 6002 10 "Scanner13 sprites/scanner" }
	{ event 6002 10 "Scanner14 sprites/scanner" }
	{ event 6002 10 "Scanner15 sprites/scanner" }
	{ event 6003 190 "Scanner1" }
	{ event 6003 190 "Scanner2" }
	{ event 6003 190 "Scanner3" }
	{ event 6003 190 "Scanner4" }
	{ event 6003 190 "Scanner5" }
	{ event 6003 190 "Scanner6" }
	{ event 6003 190 "Scanner7" }
	{ event 6003 190 "Scanner8" }
	{ event 6003 190 "Scanner9" }
	{ event 6003 190 "Scanner10" }
	{ event 6003 190 "Scanner11" }
	{ event 6003 190 "Scanner12" }
	{ event 6003 190 "Scanner13" }
	{ event 6003 190 "Scanner14" }
	{ event 6003 190 "Scanner15" }
	{ event 6002 210 "Scanner1 sprites/scanner" }
	{ event 6002 210 "Scanner2 sprites/scanner" }
	{ event 6002 210 "Scanner3 sprites/scanner" }
	{ event 6002 210 "Scanner4 sprites/scanner" }
	{ event 6002 210 "Scanner5 sprites/scanner" }
	{ event 6002 210 "Scanner6 sprites/scanner" }
	{ event 6002 210 "Scanner7 sprites/scanner" }
	{ event 6002 210 "Scanner8 sprites/scanner" }
	{ event 6002 210 "Scanner9 sprites/scanner" }
	{ event 6002 210 "Scanner10 sprites/scanner" }
	{ event 6002 210 "Scanner11 sprites/scanner" }
	{ event 6002 210 "Scanner12 sprites/scanner" }
	{ event 6002 210 "Scanner13 sprites/scanner" }
	{ event 6002 210 "Scanner14 sprites/scanner" }
	{ event 6002 210 "Scanner15 sprites/scanner" }
	{ event 6003 390 "Scanner1" }
	{ event 6003 390 "Scanner2" }
	{ event 6003 390 "Scanner3" }
	{ event 6003 390 "Scanner4" }
	{ event 6003 390 "Scanner5" }
	{ event 6003 390 "Scanner6" }
	{ event 6003 390 "Scanner7" }
	{ event 6003 390 "Scanner8" }
	{ event 6003 390 "Scanner9" }
	{ event 6003 390 "Scanner10" }
	{ event 6003 390 "Scanner11" }
	{ event 6003 390 "Scanner12" }
	{ event 6003 390 "Scanner13" }
	{ event 6003 390 "Scanner14" }
	{ event 6003 390 "Scanner15" }
	fadein 0.2
	fadeout 0.2
	fps 17
	loop
}

$sequence "Low_Loop" {
	"scanner1_scrapyard_anims\Low_Loop.smd"
	{ event 6002 10 "Scanner1 sprites/scanner" }
	{ event 6002 10 "Scanner2 sprites/scanner" }
	{ event 6002 10 "Scanner3 sprites/scanner" }
	{ event 6002 10 "Scanner4 sprites/scanner" }
	{ event 6002 10 "Scanner5 sprites/scanner" }
	{ event 6002 10 "Scanner6 sprites/scanner" }
	{ event 6002 10 "Scanner7 sprites/scanner" }
	{ event 6002 10 "Scanner8 sprites/scanner" }
	{ event 6002 10 "Scanner9 sprites/scanner" }
	{ event 6002 10 "Scanner10 sprites/scanner" }
	{ event 6002 10 "Scanner11 sprites/scanner" }
	{ event 6002 10 "Scanner12 sprites/scanner" }
	{ event 6002 10 "Scanner13 sprites/scanner" }
	{ event 6002 10 "Scanner14 sprites/scanner" }
	{ event 6002 10 "Scanner15 sprites/scanner" }
	{ event 6003 190 "Scanner1" }
	{ event 6003 190 "Scanner2" }
	{ event 6003 190 "Scanner3" }
	{ event 6003 190 "Scanner4" }
	{ event 6003 190 "Scanner5" }
	{ event 6003 190 "Scanner6" }
	{ event 6003 190 "Scanner7" }
	{ event 6003 190 "Scanner8" }
	{ event 6003 190 "Scanner9" }
	{ event 6003 190 "Scanner10" }
	{ event 6003 190 "Scanner11" }
	{ event 6003 190 "Scanner12" }
	{ event 6003 190 "Scanner13" }
	{ event 6003 190 "Scanner14" }
	{ event 6003 190 "Scanner15" }
	{ event 6002 210 "Scanner1 sprites/scanner" }
	{ event 6002 210 "Scanner2 sprites/scanner" }
	{ event 6002 210 "Scanner3 sprites/scanner" }
	{ event 6002 210 "Scanner4 sprites/scanner" }
	{ event 6002 210 "Scanner5 sprites/scanner" }
	{ event 6002 210 "Scanner6 sprites/scanner" }
	{ event 6002 210 "Scanner7 sprites/scanner" }
	{ event 6002 210 "Scanner8 sprites/scanner" }
	{ event 6002 210 "Scanner9 sprites/scanner" }
	{ event 6002 210 "Scanner10 sprites/scanner" }
	{ event 6002 210 "Scanner11 sprites/scanner" }
	{ event 6002 210 "Scanner12 sprites/scanner" }
	{ event 6002 210 "Scanner13 sprites/scanner" }
	{ event 6002 210 "Scanner14 sprites/scanner" }
	{ event 6002 210 "Scanner15 sprites/scanner" }
	{ event 6003 390 "Scanner1" }
	{ event 6003 390 "Scanner2" }
	{ event 6003 390 "Scanner3" }
	{ event 6003 390 "Scanner4" }
	{ event 6003 390 "Scanner5" }
	{ event 6003 390 "Scanner6" }
	{ event 6003 390 "Scanner7" }
	{ event 6003 390 "Scanner8" }
	{ event 6003 390 "Scanner9" }
	{ event 6003 390 "Scanner10" }
	{ event 6003 390 "Scanner11" }
	{ event 6003 390 "Scanner12" }
	{ event 6003 390 "Scanner13" }
	{ event 6003 390 "Scanner14" }
	{ event 6003 390 "Scanner15" }
	fadein 0.2
	fadeout 0.2
	fps 25
	loop
}
