// Created by Crowbar 0.74

// Stored modelname (without quotes): "tfc/models/Detpack.mdl"
$modelname "detpack.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "Detpack_Template1"
}

$flags 0


$attachment 0 "01" 0 0 10.5

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "01" -16.360001 -8.03 -10.87 15.9 7.12 11.94

$sequence "idle" {
	"detpack_anims\idle"
	fps 10
	loop
}
