// Created by Crowbar 0.74

// Stored modelname (without quotes): "tf1/models/p_sniper.mdl"
$modelname "p_sniper2.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "p_sniper_reference"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -1.923021 0 -4.140393 0 2.549738 0
$hbox 0 "Box02" -27.959999 -8.63 -0.55 19.15 3.36 2.15

$sequence "standthere" {
	"p_sniper2_anims\standthere"
	fps 30
}
