// Created by Crowbar 0.74

// Stored modelname (without quotes): "c:\engines\workHL\tfc\models\p_sniper.mdl"
$modelname "p_sniper.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "sniper"
}

$flags 0


$attachment 0 "Bip01 R Hand" 31.330099 -1.34241 3.26817

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -2.869897 0 -4.140396 0 1.399659 0
$hbox 0 "02" -1.41 -19.440001 -4.92 1.59 21.190001 4.62

$sequence "dummyidle" {
	"p_sniper_anims\dummyidle"
	fps 30
}
