// Created by Crowbar 0.74

// Stored modelname (without quotes): "tf1/models/p_spanner.mdl"
$modelname "p_spanner2.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "p_spanner"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -1.923021 0 -4.140394 0 2.549736 0
$hbox 0 "Bip01 R Hand" 0 0 0 2.89864 1.113592 3.088764
$hbox 0 "Hands Mesh01" -0.9 -8.33 -1.56 0.9 8.33 1.55

$sequence "standthere" {
	"p_spanner2_anims\standthere"
	fps 30
}
