// Created by Crowbar 0.74

// Stored modelname (without quotes): "c:\engines\workHL\tfc\models\p_Srpg.mdl"
$modelname "p_srpg.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "s_rpg"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -3.283119 -1.707181 -3.692527 0 0 0
$hbox 0 "Object02" -19.139999 -3.34 -3.8 19.129999 3.34 5.13

$sequence "dummyidle" {
	"p_srpg_anims\dummyidle"
	fps 30
}
