// Created by Crowbar 0.74

// Stored modelname (without quotes): "c:\sierra\half-life\valve\models\w_rpg.mdl"
$modelname "w_rpg.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "w_rpg_reference"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "rlauncher" -6.86 -34.560001 -12.6 6.86 34.560001 12.6

$sequence "idle1" {
	"w_rpg_anims\idle1"
	fps 30
	loop
}
