// Created by Crowbar 0.74

// Stored modelname (without quotes): "u:\dod\models\weapon\p_models\mdl\p_brensr.mdl"
$modelname "p_brensr.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "p_brensr_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box02" -5.77 -13.18 -8.62 5.07 34.700001 13.98

$sequence "p_brensr_idle" {
	"p_brensr_anims\p_brensr_idle"
	fps 1
}
