// Created by Crowbar 0.74

// Stored modelname (without quotes): "u:\dod\models\weapon\p_models\mdl\p_grease_l.mdl"
$modelname "p_grease_l.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "p_grease_l_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "p_greasegun" -1.05 -17.27 -6.22 1.26 12.3 6.7

$sequence "p_grease_l_idle" {
	"p_grease_l_anims\p_grease_l_idle"
	fps 1
}
