// Created by Crowbar 0.74

// Stored modelname (without quotes): "u:\dod\models\weapon\p_models\mdl\p_m1carb_l.mdl"
$modelname "p_m1carb_l.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "p_m1carb_l_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 L Hand" 0 0 0 1.924857 2.937403 3.639441
$hbox 0 "Box03" -0.75 -23.540001 -5.34 1.02 20.190001 2.68

$sequence "p_m1carb_l_idle" {
	"p_m1carb_l_anims\p_m1carb_l_idle"
	fps 1
}
