// Created by Crowbar 0.74

// Stored modelname (without quotes): "H:\beta2\models\axis\weapons\mg34\p_mg34sr.mdl"
$modelname "p_mg34sr.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "p_mg34sr_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "p_mg34" -41.360001 -6.05 -2.95 15.21 2.76 1.68

$sequence "p_mg34sr_idle" {
	"p_mg34sr_anims\p_mg34sr_idle"
	fps 5
}
