// Created by Crowbar 0.74

// Stored modelname (without quotes): "u:\dod\models\weapon\p_models\mdl\w_stg44.mdl"
$modelname "w_mp44.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_stg44_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "skin" -0.61 -25.110001 -7.05 0.89 11.6 7

$sequence "w_stg44_idle" {
	"w_mp44_anims\w_stg44_idle"
	fps 1
}
