// Created by Crowbar 0.74

// Stored modelname (without quotes): "u:\dod\models\weapon\p_models\piat\w_piat.mdl"
$modelname "w_piat.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_piat_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "piat" -2.54 -7.94 -14.95 2.18 9.23 21.040001

$sequence "w_piat_idle" {
	"w_piat_anims\w_piat_idle"
	fps 10
}
