// Created by Crowbar 0.74

// Stored modelname (without quotes): "u:\dod\models\weapon\p_models\mdl\w_pschreck_rocket.mdl"
$modelname "w_pschreck_rocket.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_pschreck_rocket_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "rocket" -8.54 -1.6 -1.63 11.91 1.65 1.62

$sequence "w_pschreck_rocket_idle" {
	"w_pschreck_rocket_anims\w_pschreck_rocket_idle"
	fps 10
}
