// Created by Crowbar 0.74

$modelname "striderbustervendor1/wall2c.mdl"

$bodygroup "studio"
{
	studio "wall2c.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\striderbustervendor1\"

$cbox 0 0 0 0 0 0

$bbox -138 -12 128 374 -11 384

$definebone "c" "" 3008.5 352 366 0 0 0 0 0 0 0 0 0
$definebone "debris2_367_loc" "c" 0 127 16 0 0 0 0 0 0 0 0 0
$definebone "debris2_366_loc" "c" 0 126.75 -112 0 0 0 0 0 0 0 0 0
$definebone "debris2_365_loc" "c" 0 126.75 -26.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_364_loc" "c" 0 125 14 0 0 0 0 0 0 0 0 0
$definebone "debris2_363_loc" "c" 0 122 -32.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_362_loc" "c" 0 120.25 -141 0 0 0 0 0 0 0 0 0
$definebone "debris2_361_loc" "c" 0 112.75 -145 0 0 0 0 0 0 0 0 0
$definebone "debris2_360_loc" "c" 0 111.5 -143.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_359_loc" "c" 0 111.75 -138.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_358_loc" "c" 0 115.75 -150 0 0 0 0 0 0 0 0 0
$definebone "debris2_357_loc" "c" 0 114.5 -23 0 0 0 0 0 0 0 0 0
$definebone "debris2_356_loc" "c" 0 112 -102.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_355_loc" "c" 0 112 -120 0 0 0 0 0 0 0 0 0
$definebone "debris2_354_loc" "c" 0 112 -91.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_353_loc" "c" 0 112 -52.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_352_loc" "c" 0 112 -62 0 0 0 0 0 0 0 0 0
$definebone "debris2_351_loc" "c" 0 112 -76.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_350_loc" "c" 0 109.5 -13 0 0 0 0 0 0 0 0 0
$definebone "debris2_349_loc" "c" 0 108.5 -43 0 0 0 0 0 0 0 0 0
$definebone "debris2_348_loc" "c" 0 83.5 -15 0 0 0 0 0 0 0 0 0
$definebone "debris2_347_loc" "c" 0 89 -20.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_346_loc" "c" 0 81.75 -13 0 0 0 0 0 0 0 0 0
$definebone "debris2_345_loc" "c" 0 72.75 -10.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_343_loc" "c" 0 82 -121 0 0 0 0 0 0 0 0 0
$definebone "debris2_342_loc" "c" 0 68.25 -15.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_341_loc" "c" 0 77 -40 0 0 0 0 0 0 0 0 0
$definebone "debris2_339_loc" "c" 0 89.75 -130.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_336_loc" "c" 0 63.5 -20.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_335_loc" "c" 0 46.5 -39.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_333_loc" "c" 0 28.75 -72 0 0 0 0 0 0 0 0 0
$definebone "debris2_332_loc" "c" 0 28.5 -92 0 0 0 0 0 0 0 0 0
$definebone "debris2_331_loc" "c" 0 75.25 -111 0 0 0 0 0 0 0 0 0
$definebone "debris2_329_loc" "c" 0 60 -100.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_328_loc" "c" 0 20.25 -81.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_327_loc" "c" 0 18.25 -52.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_324_loc" "c" 0 12 -72.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_323_loc" "c" 0 51.5 -32.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_322_loc" "c" 0 -3.75 -91 0 0 0 0 0 0 0 0 0
$definebone "debris2_320_loc" "c" 0 -35 -78.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_319_loc" "c" 0 -15.75 -52 0 0 0 0 0 0 0 0 0
$definebone "debris2_314_loc" "c" 0 -45.5 -91.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_313_loc" "c" 0 -17 -42 0 0 0 0 0 0 0 0 0
$definebone "debris2_311_loc" "c" 0 -67.75 -91.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_310_loc" "c" 0 -35.25 -72 0 0 0 0 0 0 0 0 0
$definebone "debris2_309_loc" "c" 0 -98 -81 0 0 0 0 0 0 0 0 0
$definebone "debris2_305_loc" "c" 0 -102.25 -67 0 0 0 0 0 0 0 0 0
$definebone "debris2_304_loc" "c" 0 -120.75 -82 0 0 0 0 0 0 0 0 0
$definebone "debris2_303_loc" "c" 0 -101 -92 0 0 0 0 0 0 0 0 0
$definebone "debris2_286_loc" "c" 0 -127.25 -62 0 0 0 0 0 0 0 0 0
$definebone "debris2_285_loc" "c" 0 -127.25 -72 0 0 0 0 0 0 0 0 0
$definebone "debris2_284_loc" "c" 0 -127.25 -79.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_283_loc" "c" 0 -127.25 -89 0 0 0 0 0 0 0 0 0
$definebone "debris2_280_loc" "c" 0 126.75 -368.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_279_loc" "c" 0 127 -452.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_277_loc" "c" 0 126.75 -199.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_276_loc" "c" 0 125.75 -259 0 0 0 0 0 0 0 0 0
$definebone "debris2_275_loc" "c" 0 122.5 -452.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_273_loc" "c" 0 123.25 -180.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_272_loc" "c" 0 121 -273.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_271_loc" "c" 0 122.5 -308.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_270_loc" "c" 0 122 -161 0 0 0 0 0 0 0 0 0
$definebone "debris2_269_loc" "c" 0 121.5 -416 0 0 0 0 0 0 0 0 0
$definebone "debris2_267_loc" "c" 0 116 -407.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_266_loc" "c" 0 103 -148.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_265_loc" "c" 0 103.75 -272 0 0 0 0 0 0 0 0 0
$definebone "debris2_264_loc" "c" 0 103.25 -277 0 0 0 0 0 0 0 0 0
$definebone "debris2_263_loc" "c" 0 104.75 -143 0 0 0 0 0 0 0 0 0
$definebone "debris2_262_loc" "c" 0 101.75 -272.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_261_loc" "c" 0 103.75 -139 0 0 0 0 0 0 0 0 0
$definebone "debris2_260_loc" "c" 0 102.75 -406 0 0 0 0 0 0 0 0 0
$definebone "debris2_258_loc" "c" 0 98 -144 0 0 0 0 0 0 0 0 0
$definebone "debris2_257_loc" "c" 0 111 -200 0 0 0 0 0 0 0 0 0
$definebone "debris2_256_loc" "c" 0 112.25 -210 0 0 0 0 0 0 0 0 0
$definebone "debris2_255_loc" "c" 0 112.25 -220 0 0 0 0 0 0 0 0 0
$definebone "debris2_254_loc" "c" 0 111.75 -318 0 0 0 0 0 0 0 0 0
$definebone "debris2_253_loc" "c" 0 111.75 -359.5 0 0 0 0 0 0 0 0 0
$definebone "debris2_252_loc" "c" 0 111 -367 0 0 0 0 0 0 0 0 0
$definebone "debris2_251_loc" "c" 0 111.75 -376 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_268_loc" "c" 0 115.75 -278.5 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_243_loc" "c" 0 85.5 -271.5 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_92_loc" "c" 0 -95.25 -305.5 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_45_loc" "c" 0 -83.25 -304 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_12_loc" "c" 0 -127.5 -307 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_259_loc" "c" 0 112 -239 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_278_loc" "c" 0 126.75 -282.5 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_274_loc" "c" 0 124.25 -337.5 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_48_loc" "c" 0 -113.75 -268 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_49_loc" "c" 0 -115.75 -258.5 0 0 0 0 0 0 0 0 0
$definebone "tweaked_debris2_71_loc" "c" 0 -106.5 -272 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "c" position rotation
$bonesaveframe "debris2_367_loc" position rotation
$bonesaveframe "debris2_366_loc" position rotation
$bonesaveframe "debris2_365_loc" position rotation
$bonesaveframe "debris2_364_loc" position rotation
$bonesaveframe "debris2_363_loc" position rotation
$bonesaveframe "debris2_362_loc" position rotation
$bonesaveframe "debris2_361_loc" position rotation
$bonesaveframe "debris2_360_loc" position rotation
$bonesaveframe "debris2_359_loc" position rotation
$bonesaveframe "debris2_358_loc" position rotation
$bonesaveframe "debris2_357_loc" position rotation
$bonesaveframe "debris2_356_loc" position rotation
$bonesaveframe "debris2_355_loc" position rotation
$bonesaveframe "debris2_354_loc" position rotation
$bonesaveframe "debris2_353_loc" position rotation
$bonesaveframe "debris2_352_loc" position rotation
$bonesaveframe "debris2_351_loc" position rotation
$bonesaveframe "debris2_350_loc" position rotation
$bonesaveframe "debris2_349_loc" position rotation
$bonesaveframe "debris2_348_loc" position rotation
$bonesaveframe "debris2_347_loc" position rotation
$bonesaveframe "debris2_346_loc" position rotation
$bonesaveframe "debris2_345_loc" rotation
$bonesaveframe "debris2_343_loc" position rotation
$bonesaveframe "debris2_342_loc" position rotation
$bonesaveframe "debris2_341_loc" position rotation
$bonesaveframe "debris2_339_loc" position rotation
$bonesaveframe "debris2_336_loc" position rotation
$bonesaveframe "debris2_335_loc" position rotation
$bonesaveframe "debris2_333_loc" position rotation
$bonesaveframe "debris2_332_loc" position rotation
$bonesaveframe "debris2_331_loc" position rotation
$bonesaveframe "debris2_329_loc" position rotation
$bonesaveframe "debris2_328_loc" position rotation
$bonesaveframe "debris2_327_loc" position rotation
$bonesaveframe "debris2_324_loc" position rotation
$bonesaveframe "debris2_323_loc" position rotation
$bonesaveframe "debris2_322_loc" position rotation
$bonesaveframe "debris2_320_loc" position rotation
$bonesaveframe "debris2_319_loc" position rotation
$bonesaveframe "debris2_314_loc" position rotation
$bonesaveframe "debris2_313_loc" position rotation
$bonesaveframe "debris2_311_loc" position rotation
$bonesaveframe "debris2_310_loc" position rotation
$bonesaveframe "debris2_309_loc" position rotation
$bonesaveframe "debris2_305_loc" position rotation
$bonesaveframe "debris2_304_loc" position rotation
$bonesaveframe "debris2_303_loc" position rotation
$bonesaveframe "debris2_286_loc" rotation
$bonesaveframe "debris2_285_loc" position rotation
$bonesaveframe "debris2_284_loc" position rotation
$bonesaveframe "debris2_283_loc" position rotation
$bonesaveframe "debris2_280_loc" position rotation
$bonesaveframe "debris2_279_loc" position rotation
$bonesaveframe "debris2_277_loc" position rotation
$bonesaveframe "debris2_276_loc" position rotation
$bonesaveframe "debris2_275_loc" position rotation
$bonesaveframe "debris2_273_loc" position rotation
$bonesaveframe "debris2_272_loc" position rotation
$bonesaveframe "debris2_271_loc" position rotation
$bonesaveframe "debris2_270_loc" position rotation
$bonesaveframe "debris2_269_loc" position rotation
$bonesaveframe "debris2_267_loc" position rotation
$bonesaveframe "debris2_266_loc" position rotation
$bonesaveframe "debris2_265_loc" position rotation
$bonesaveframe "debris2_264_loc" position rotation
$bonesaveframe "debris2_263_loc" position rotation
$bonesaveframe "debris2_262_loc" position rotation
$bonesaveframe "debris2_261_loc" position rotation
$bonesaveframe "debris2_260_loc" position rotation
$bonesaveframe "debris2_258_loc" position rotation
$bonesaveframe "debris2_257_loc" position rotation
$bonesaveframe "debris2_256_loc" position rotation
$bonesaveframe "debris2_255_loc" position rotation
$bonesaveframe "debris2_254_loc" position rotation
$bonesaveframe "debris2_253_loc" position rotation
$bonesaveframe "debris2_252_loc" position rotation
$bonesaveframe "debris2_251_loc" position rotation
$bonesaveframe "tweaked_debris2_268_loc" position rotation
$bonesaveframe "tweaked_debris2_243_loc" position rotation
$bonesaveframe "tweaked_debris2_92_loc" position rotation
$bonesaveframe "tweaked_debris2_45_loc" position rotation
$bonesaveframe "tweaked_debris2_12_loc" position rotation
$bonesaveframe "tweaked_debris2_259_loc" position rotation
$bonesaveframe "tweaked_debris2_278_loc" position rotation
$bonesaveframe "tweaked_debris2_274_loc" position rotation
$bonesaveframe "tweaked_debris2_48_loc" position rotation
$bonesaveframe "tweaked_debris2_49_loc" position rotation
$bonesaveframe "tweaked_debris2_71_loc" position rotation

$sectionframes 30 298

$sequence "idle" {
	"wall2c_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "explode" {
	"wall2c_anims\explode.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "exploded" {
	"wall2c_anims\exploded.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}
