// Created by Crowbar 0.74

$modelname "striderbustervendor1/wall7b.mdl"

$bodygroup "studio"
{
	studio "wall7b.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\striderbustervendor1\"

$cbox 0 0 0 0 0 0

$bbox -266 -12.001 0 118 -11 128

$definebone "b" "" 3008.499512 145.5 -24 0 0 0 0 0 0 0 0 0
$definebone "debris7_195_loc" "b" 0.000488 77.75 121.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_194_loc" "b" 0.000488 77.75 -17.625 0 0 0 0 0 0 0 0 0
$definebone "debris7_193_loc" "b" 0.000488 77.5 -35.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_192_loc" "b" 0.000488 77.75 -97.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_191_loc" "b" 0.000488 77.5 -20.625 0 0 0 0 0 0 0 0 0
$definebone "debris7_190_loc" "b" 0.000488 77.5 -103.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_189_loc" "b" 0.000488 78 -114.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_188_loc" "b" 0.000488 76.5 156.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_187_loc" "b" 0.000488 77.25 40.5 0 0 0 0 0 0 0 0 0
$definebone "debris7_186_loc" "b" 0.000488 76 28.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_185_loc" "b" 0.000488 77.5 -9 0 0 0 0 0 0 0 0 0
$definebone "debris7_184_loc" "b" 0.000488 76.75 -27 0 0 0 0 0 0 0 0 0
$definebone "debris7_183_loc" "b" 0.000488 76.5 -55.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_182_loc" "b" 0.000488 77.25 99.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_181_loc" "b" 0.000488 76.5 87 0 0 0 0 0 0 0 0 0
$definebone "debris7_180_loc" "b" 0.000488 76.75 53.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_179_loc" "b" 0.000488 77 -137.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_178_loc" "b" 0.000488 77 -142.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_177_loc" "b" 0.000488 75.25 29.625 0 0 0 0 0 0 0 0 0
$definebone "debris7_176_loc" "b" 0.000488 76.25 22.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_175_loc" "b" 0.000488 76.25 -143.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_174_loc" "b" 0.000488 75.75 187.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_173_loc" "b" 0.000488 76.5 171.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_172_loc" "b" 0.000488 75.25 167.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_171_loc" "b" 0.000488 75.75 112.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_170_loc" "b" 0.000488 76 65.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_169_loc" "b" 0.000488 76.25 58.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_168_loc" "b" 0.000488 76.25 48.375 0 0 0 0 0 0 0 0 0
$definebone "debris7_167_loc" "b" 0.000488 76.5 44.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_166_loc" "b" 0.000488 75 39 0 0 0 0 0 0 0 0 0
$definebone "debris7_165_loc" "b" 0.000488 76.75 -47.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_164_loc" "b" 0.000488 76.25 -90.375 0 0 0 0 0 0 0 0 0
$definebone "debris7_163_loc" "b" 0.000488 75.5 -97.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_162_loc" "b" 0.000488 75.75 164.625 0 0 0 0 0 0 0 0 0
$definebone "debris7_161_loc" "b" 0.000488 75.75 77.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_160_loc" "b" 0.000488 76.25 34.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_159_loc" "b" 0.000488 75.75 13.5 0 0 0 0 0 0 0 0 0
$definebone "debris7_158_loc" "b" 0.000488 75.5 -70.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_157_loc" "b" 0.000488 75.75 -85.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_156_loc" "b" 0.000488 76 -128.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_155_loc" "b" 0.000488 75.75 -154.5 0 0 0 0 0 0 0 0 0
$definebone "debris7_154_loc" "b" 0.000488 76 -183 0 0 0 0 0 0 0 0 0
$definebone "debris7_153_loc" "b" 0.000488 75.5 177.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_152_loc" "b" 0.000488 75.5 138.375 0 0 0 0 0 0 0 0 0
$definebone "debris7_151_loc" "b" 0.000488 74.5 45.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_150_loc" "b" 0.000488 75.25 -0.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_149_loc" "b" 0.000488 74.5 168.375 0 0 0 0 0 0 0 0 0
$definebone "debris7_148_loc" "b" 0.000488 74 112.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_147_loc" "b" 0.000488 73.75 52.5 0 0 0 0 0 0 0 0 0
$definebone "debris7_146_loc" "b" 0.000488 74.75 41.625 0 0 0 0 0 0 0 0 0
$definebone "debris7_145_loc" "b" 0.000488 74.75 -87.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_144_loc" "b" 0.000488 74.25 -134.625 0 0 0 0 0 0 0 0 0
$definebone "debris7_143_loc" "b" 0.000488 74.75 -168.75 0 0 0 0 0 0 0 0 0
$definebone "debris7_142_loc" "b" 0.000488 74.5 94.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_141_loc" "b" 0.000488 73.5 -15.375 0 0 0 0 0 0 0 0 0
$definebone "debris7_140_loc" "b" 0.000488 75.5 -40.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_139_loc" "b" 0.000488 74 -52.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_138_loc" "b" 0.000488 73.5 147 0 0 0 0 0 0 0 0 0
$definebone "debris7_137_loc" "b" 0.000488 72.25 64.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_136_loc" "b" 0.000488 73.25 13.5 0 0 0 0 0 0 0 0 0
$definebone "debris7_135_loc" "b" 0.000488 73.25 -30 0 0 0 0 0 0 0 0 0
$definebone "debris7_134_loc" "b" 0.000488 73.25 -71.25 0 0 0 0 0 0 0 0 0
$definebone "debris7_133_loc" "b" 0.000488 73 -79.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_132_loc" "b" 0.000488 75 -112.875 0 0 0 0 0 0 0 0 0
$definebone "debris7_131_loc" "b" 0.000488 74.5 -142.5 0 0 0 0 0 0 0 0 0
$definebone "debris7_130_loc" "b" 0.000488 72.25 112.5 0 0 0 0 0 0 0 0 0
$definebone "debris7_129_loc" "b" 0.000488 73 106.5 0 0 0 0 0 0 0 0 0
$definebone "debris7_128_loc" "b" 0.000488 71 150 0 0 0 0 0 0 0 0 0
$definebone "debris7_127_loc" "b" 0.000488 71.75 115.125 0 0 0 0 0 0 0 0 0
$definebone "debris7_126_loc" "b" 0.000488 71.5 -84.375 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "b" position rotation
$bonesaveframe "debris7_195_loc" position rotation
$bonesaveframe "debris7_194_loc" position rotation
$bonesaveframe "debris7_193_loc" position rotation
$bonesaveframe "debris7_192_loc" position rotation
$bonesaveframe "debris7_191_loc" position rotation
$bonesaveframe "debris7_190_loc" position rotation
$bonesaveframe "debris7_189_loc" position rotation
$bonesaveframe "debris7_188_loc" position rotation
$bonesaveframe "debris7_187_loc" position rotation
$bonesaveframe "debris7_186_loc" position rotation
$bonesaveframe "debris7_185_loc" position rotation
$bonesaveframe "debris7_184_loc" position rotation
$bonesaveframe "debris7_183_loc" position rotation
$bonesaveframe "debris7_182_loc" position rotation
$bonesaveframe "debris7_181_loc" position rotation
$bonesaveframe "debris7_180_loc" position rotation
$bonesaveframe "debris7_179_loc" position rotation
$bonesaveframe "debris7_178_loc" position rotation
$bonesaveframe "debris7_177_loc" position rotation
$bonesaveframe "debris7_176_loc" position rotation
$bonesaveframe "debris7_175_loc" position rotation
$bonesaveframe "debris7_174_loc" position rotation
$bonesaveframe "debris7_173_loc" position rotation
$bonesaveframe "debris7_172_loc" position rotation
$bonesaveframe "debris7_171_loc" position rotation
$bonesaveframe "debris7_170_loc" position rotation
$bonesaveframe "debris7_169_loc" position rotation
$bonesaveframe "debris7_168_loc" position rotation
$bonesaveframe "debris7_167_loc" position rotation
$bonesaveframe "debris7_166_loc" position rotation
$bonesaveframe "debris7_165_loc" position rotation
$bonesaveframe "debris7_164_loc" position rotation
$bonesaveframe "debris7_163_loc" position rotation
$bonesaveframe "debris7_162_loc" position rotation
$bonesaveframe "debris7_161_loc" position rotation
$bonesaveframe "debris7_160_loc" position rotation
$bonesaveframe "debris7_159_loc" position rotation
$bonesaveframe "debris7_158_loc" position rotation
$bonesaveframe "debris7_157_loc" position rotation
$bonesaveframe "debris7_156_loc" position rotation
$bonesaveframe "debris7_155_loc" position rotation
$bonesaveframe "debris7_154_loc" position rotation
$bonesaveframe "debris7_153_loc" position rotation
$bonesaveframe "debris7_152_loc" position rotation
$bonesaveframe "debris7_151_loc" position rotation
$bonesaveframe "debris7_150_loc" position rotation
$bonesaveframe "debris7_149_loc" position rotation
$bonesaveframe "debris7_148_loc" position rotation
$bonesaveframe "debris7_147_loc" position rotation
$bonesaveframe "debris7_146_loc" position rotation
$bonesaveframe "debris7_145_loc" position rotation
$bonesaveframe "debris7_144_loc" position rotation
$bonesaveframe "debris7_143_loc" position rotation
$bonesaveframe "debris7_142_loc" position rotation
$bonesaveframe "debris7_141_loc" position rotation
$bonesaveframe "debris7_140_loc" position rotation
$bonesaveframe "debris7_139_loc" position rotation
$bonesaveframe "debris7_138_loc" position rotation
$bonesaveframe "debris7_137_loc" position rotation
$bonesaveframe "debris7_136_loc" position rotation
$bonesaveframe "debris7_135_loc" position rotation
$bonesaveframe "debris7_134_loc" position rotation
$bonesaveframe "debris7_133_loc" position rotation
$bonesaveframe "debris7_132_loc" position rotation
$bonesaveframe "debris7_131_loc" position rotation
$bonesaveframe "debris7_130_loc" position rotation
$bonesaveframe "debris7_129_loc" position rotation
$bonesaveframe "debris7_128_loc" position rotation
$bonesaveframe "debris7_127_loc" position rotation
$bonesaveframe "debris7_126_loc" position rotation

$sectionframes 30 298

$sequence "idle" {
	"wall7b_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "explode" {
	"wall7b_anims\explode.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "exploded" {
	"wall7b_anims\exploded.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}
