// Created by Crowbar 0.74

$modelname "c5_bridge_destruction/bridge_lfttower_stat_floors.mdl"

$bodygroup "Body"
{
	studio "bridge_lfttower_stat_floors.smd"
}


$surfaceprop "metal"

$contents "solid"

$illumposition 526 2047.613 597

$cdmaterials "models\props_highway"
$cdmaterials "models\c5_bridge_destruction\"
$cdmaterials ""

$cbox 0 0 0 0 0 0

$bbox -2435.695 260 390 -1659.531 792 804

$definebone "Bridge_LeftRoadrbdCage_strut_30_JOINT" "" 337.61499 759 -1822.477539 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_9_JOINT" "" 578 746.440613 -1913.657959 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_57_JOINT" "" 302.5 467.132751 -1771.900146 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_12_JOINT" "" 420.232422 430.506836 -2137.42627 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_68_JOINT" "" 382.499756 753.440674 -2101 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_53_JOINT" "" 720.5 732.067261 -1976.563721 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_67_JOINT" "" 470.000031 746.440674 -1912.98584 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_32_JOINT" "" 687.75 741.25 -1819.680176 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_41_JOINT" "" 527.268066 430.500061 -2073.630859 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_14_JOINT" "" 395.492188 435.496582 -1962 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_45_JOINT" "" 719.385254 469.13269 -1841 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_70_JOINT" "" 420.876709 752.940674 -1810.765381 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_43_JOINT" "" 333.882813 467.132751 -1836 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_42_JOINT" "" 719.385254 469.13269 -2098 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_34_JOINT" "" 526.499512 752 -2101 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_65_JOINT" "" 738.5 598 -1770.900146 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_82_JOINT" "" 685 753.440613 -2227.375977 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_66_JOINT" "" 472.734863 742.02478 -2265.982422 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_40_JOINT" "" 333.882813 467.13269 -2098 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_80_JOINT" "" 684.5 753.440674 -1962.856201 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_59_JOINT" "" 329.5 731.0672 -1962.165039 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_50_JOINT" "" 719.385315 430.999969 -1964.900146 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_35_JOINT" "" 743.499756 761 -2102.381836 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_60_JOINT" "" 367.499756 741.25 -1723.258301 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_44_JOINT" "" 527.268311 430.500061 -1835.624634 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_64_JOINT" "" 772 551.019043 -2137.070801 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_38_JOINT" "" 333.882813 482.613525 -2164.490967 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_56_JOINT" "" 333.882813 436.474792 -1992 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_17_JOINT" "" 628.531006 443 -1763.624512 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_81_JOINT" "" 627.880859 741.25 -1819.680176 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_37_JOINT" "" 703 689.613525 -2202.179443 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_63_JOINT" "" 280 550.019043 -2128 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_31_JOINT" "" 556.000244 747.940552 -1810.765381 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_8_JOINT" "" 347.5 753.440674 -1940.208984 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_13_JOINT" "" 629.169434 431 -2137.42627 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_36_JOINT" "" 334.640381 689.613464 -2263.461914 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_16_JOINT" "" 420.232452 435.496582 -1763.624512 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_11_JOINT" "" 573.000244 742.02478 -2265.982422 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_10_JOINT" "" 367.000244 749.024719 -2265.338135 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_62_JOINT" "" 282.499268 539.864136 -1852.37207 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_83_JOINT" "" 669.999756 753.440674 -2101 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_15_JOINT" "" 621.169189 430.999939 -1937.190918 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_33_JOINT" "" 308.999756 760 -2102.381836 0 0 0 0 0 0 0 0 0
$definebone "Bridge_LeftRoadrbdCage_strut_39_JOINT" "" 719.385498 483.613525 -2162 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "Bridge_LeftRoadrbdCage_strut_30_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_9_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_57_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_12_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_68_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_53_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_67_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_32_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_41_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_14_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_45_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_70_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_43_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_42_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_34_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_65_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_82_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_66_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_40_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_80_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_59_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_50_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_35_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_60_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_44_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_64_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_38_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_56_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_17_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_81_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_37_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_63_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_31_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_8_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_13_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_36_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_16_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_11_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_10_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_62_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_83_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_15_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_33_JOINT" position
$bonesaveframe "Bridge_LeftRoadrbdCage_strut_39_JOINT" position

$sectionframes 30 249

$sequence "idle" {
	"bridge_lfttower_stat_floors_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "hit" {
	"bridge_lfttower_stat_floors_anims\hit.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "end" {
	"bridge_lfttower_stat_floors_anims\end.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
