// Created by Crowbar 0.74

$modelname "c1_chargerexit/doors_glass_3.mdl"

$bodygroup "Body"
{
	studio "doors_glass_3.smd"
}


$surfaceprop "glass"

$contents "solid"

$illumposition -187.257 -18.289 23.306

$cdmaterials "models\props_doors"
$cdmaterials ""

$cbox 0 0 0 0 0 0

$bbox -5.283 -187.624 7.401 41.861 -186.889 39.211

$definebone "baked_cent_bot_glass_4_Primary369" "" -187.256592 29.058548 24.575081 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary368" "" -187.256592 36.841873 27.194214 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3590" "" -187.256592 35.149845 36.62307 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary365" "" -187.256592 34.81144 28.241867 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary367" "" -187.256592 38.533905 27.194214 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary366" "" -187.256592 37.85709 29.813347 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary431" "" -187.256592 14.84551 -4.235352 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary416" "" -187.256592 20.598406 4.669693 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary415" "" -187.256592 19.244783 2.574394 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary414" "" -187.256592 18.906378 5.717346 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary413" "" -187.256592 31.427387 6.24118 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary412" "" -187.256592 27.704924 2.574387 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary411" "" -187.256592 35.488251 5.717346 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary410" "" -187.256592 30.073765 7.288818 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3620" "" -187.256592 38.533905 32.956299 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary422" "" -187.256592 37.857094 1.526733 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary428" "" -187.256592 24.997679 -3.187683 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary419" "" -187.256592 24.320868 2.05056 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary418" "" -187.256592 11.123047 -0.56855 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3540" "" -187.256592 16.199133 37.670731 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary403" "" -187.256592 32.781029 10.955605 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3630" "" -187.256592 16.875944 32.956291 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary430" "" -187.256592 31.088982 -3.187683 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3560" "" -187.256592 33.457817 40.289856 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary417" "" -187.256592 31.765793 3.62204 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary392" "" -187.256592 32.104198 14.622391 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary389" "" -187.256592 28.043331 15.670044 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary388" "" -187.256592 24.659273 15.670044 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary387" "" -187.256592 15.522322 15.670044 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary386" "" -187.256592 12.138265 15.670044 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary385" "" -187.256592 8.754208 15.670044 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary384" "" -187.256592 36.503468 17.241516 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary383" "" -187.256592 26.351301 17.241508 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary382" "" -187.256592 31.765793 18.289169 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary381" "" -187.256592 13.491888 17.241516 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary380" "" -187.256592 38.195499 18.812988 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3580" "" -187.256592 38.533905 39.766037 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary378" "" -187.256592 9.092613 19.336823 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary379" "" -187.256592 29.735359 19.336823 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary376" "" -187.256592 21.952028 18.289154 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary377" "" -187.256592 33.796223 19.860641 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary374" "" -187.256592 37.180279 21.955963 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary375" "" -187.256592 31.765793 21.955948 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary372" "" -187.256592 16.537539 20.908302 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary373" "" -187.256592 33.796223 23.527435 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary370" "" -187.256592 13.830293 22.47979 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary371" "" -187.256592 23.982462 21.955956 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary408" "" -187.256592 10.784642 6.241165 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary409" "" -187.256592 16.875944 7.812653 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary420" "" -187.256592 30.750576 2.050568 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary421" "" -187.256592 33.119411 0.47908 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary426" "" -187.256592 30.41217 -1.092392 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary427" "" -187.256592 34.81144 -2.140045 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary424" "" -187.256592 26.012896 -0.044739 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary425" "" -187.256592 19.583187 -2.663872 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary400" "" -187.256592 23.305651 12.003265 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary401" "" -187.256592 30.073765 12.00325 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary402" "" -187.256592 19.244783 9.907959 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary429" "" -187.256592 37.85709 -3.187698 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary404" "" -187.256592 12.47667 8.336487 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary405" "" -187.256592 22.290434 7.288811 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary406" "" -187.256592 36.503468 9.907951 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary407" "" -187.256592 32.442604 8.336479 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary390" "" -187.256592 9.431019 13.574738 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary391" "" -187.256592 18.229567 14.622391 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3600" "" -187.256592 29.396954 32.432472 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary393" "" -187.256592 14.168699 12.00325 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary394" "" -187.256592 22.290434 13.57473 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary395" "" -187.256592 33.796223 13.050911 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary396" "" -187.256592 36.841873 12.003258 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary397" "" -187.256592 20.936811 12.00325 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary398" "" -187.256592 27.366518 10.955612 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary399" "" -187.256592 28.720142 13.050903 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3640" "" -187.256592 18.229567 27.71804 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3550" "" -187.256592 26.689707 39.242203 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary432" "" -187.256592 26.689707 -4.235352 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3570" "" -187.256592 11.461452 31.908646 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary423" "" -187.256592 15.522322 -0.568558 0 0 0 0 0 0 0 0 0
$definebone "baked_cent_bot_glass_4_Primary3610" "" -187.256592 22.628839 31.908646 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "baked_cent_bot_glass_4_Primary369" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary368" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3590" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary365" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary367" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary366" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary431" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary416" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary415" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary414" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary413" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary412" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary411" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary410" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3620" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary422" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary428" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary419" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary418" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3540" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary403" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3630" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary430" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3560" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary417" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary392" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary389" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary388" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary387" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary386" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary385" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary384" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary383" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary382" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary381" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary380" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3580" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary378" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary379" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary376" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary377" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary374" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary375" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary372" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary373" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary370" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary371" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary408" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary409" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary420" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary421" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary426" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary427" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary424" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary425" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary400" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary401" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary402" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary429" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary404" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary405" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary406" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary407" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary390" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary391" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3600" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary393" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary394" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary395" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary396" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary397" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary398" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary399" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3640" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3550" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary432" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3570" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary423" position rotation
$bonesaveframe "baked_cent_bot_glass_4_Primary3610" position rotation

$sectionframes 30 230

$sequence "idle" {
	"doors_glass_3_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "escape_a" {
	"doors_glass_3_anims\escape_a.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "escape_b" {
	"doors_glass_3_anims\escape_b.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "end" {
	"doors_glass_3_anims\end.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "endb" {
	"doors_glass_3_anims\endb.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
