// Created by Crowbar 0.74

// Stored modelname (without quotes): "valve/models/bm_sack.mdl"
$modelname "bm_sack.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "parts"
{
	studio "big_mom_sacgib"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Big Mama01" -41.599998 -50.709999 -19.450001 41.599998 47.259998 20.469999

$sequence "idle1" {
	"bm_sack_anims\idle1"
	fps 30
}
