// Created by Crowbar 0.74

// Stored modelname (without quotes): "valve/models/bonegibs.mdl"
$modelname "bonegibs.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "parts"
{
	studio "bone1"
	studio "bone2"
	studio "bone3"
	studio "bone4"
	studio "bone5"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "01" -7.6 -3.76 -0.02 15.5 1.13 4.04
$hbox 0 "" -24.17 -13.86 0 15.85 9.33 17.49
$hbox 0 "" -2.62 18.860001 -4.73 3.19 36.040001 2.96

$sequence "idle1" {
	"bonegibs_anims\idle1"
	fps 30
}
