// Created by Crowbar 0.74

// Stored modelname (without quotes): "valve/models/w_isotopebox.mdl"
$modelname "w_isotopebox.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "isotope_container"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -19.34 -16.549999 0 19.34 15.28 26.18

$sequence "idle" {
	"w_isotopebox_anims\idle"
	fps 30
}
