// Created by Crowbar 0.74

// Stored modelname (without quotes): "valve/models/w_longjump.mdl"
$modelname "w_longjump.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "longjump"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "CYLINDER01" -13.17 -8.97 -16.82 13.53 11.69 19.469999

$sequence "idle" {
	"w_longjump_anims\idle"
	fps 30
}
