// Created by Crowbar 0.74

// Stored modelname (without quotes): "valve/models/w_silencer.mdl"
$modelname "w_silencer.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "wrld_silencer"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "sides01" -7.38 -1.41 -4.74 18.469999 1.41 4.74

$sequence "idle" {
	"w_silencer_anims\idle"
	fps 30
}
