// Created by Crowbar 0.74

// Stored modelname (without quotes): "lamp_wall-hanging/lamp_wall-hanging.mdl"
$modelname "lamp_wall-hanging.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "lamp_wall-hanging"
}

$flags 0

$texrendermode "lamp2.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "lamp_wall-hanging" -12.23 -0.1 -10.3 10.21 16.450001 10.31

$sequence "idle" {
	"lamp_wall-hanging_anims\idle"
	fps 1
}
