// Created by Crowbar 0.74

// Stored modelname (without quotes): "roofridge_asian/roofridge_asian.mdl"
$modelname "roofridge_asian.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "roofridge_asian"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder03" -10.02 -8.25 -25.51 9.76 186.860001 77.889999

$sequence "idle" {
	"roofridge_asian_anims\idle"
	fps 1
}
