// Created by Crowbar 0.74

// Stored modelname (without quotes): "umbrella_cafe/umbrella_cafe.mdl"
$modelname "umbrella_cafe.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "umbrella_cafe"
}

$flags 0

$texrendermode "umbrella_cafe.bmp" masked

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box02" -37.68 0 -37.209999 36.290001 67.580002 37.209999

$sequence "idle" {
	"umbrella_cafe_anims\idle"
	fps 1
	loop
}
