// Created by Crowbar 0.74

// Stored modelname (without quotes): "gibs_debris.mdl"
$modelname "gibs_wallorange.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "gibs"
{
	studio "gib1"
	studio "gib2"
	studio "gib3"
	studio "gib4"
	studio "gib5"
	studio "gib6"
	studio "gib7"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "gib" -10.66 -12.92 -0.76 9.87 11.49 13.28

$sequence "idle" {
	"gibs_wallorange_anims\idle"
	fps 1
}
