// Created by Crowbar 0.74

$modelname "p_p90.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "p_p90"
}

$flags 0


$attachment 0 "flash" 0 0 0

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 R Hand" 0 0 0 12.77309 3.339208 3.322692
$hbox 0 "flash" -1.947984 0 0 0 7.077577 4.476907
$hbox 0 "p 90" 0 -6.38 -8.43 3.12 16.77 0

$sequence "idle" {
	"p_p90_anims\idle"
	fps 30
}
