// Created by Crowbar 0.74

// Stored modelname (without quotes): "u:\hl1\models\dmc\world_models\wrld_ssg\g_shot2.mdl"
$modelname "g_shot2.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_DMC_ssg"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -5.9 -21.18 0 5.9 21.18 37.66

$sequence "idle" {
	"g_shot2_anims\idle"
	fps 30
}
