// Created by Crowbar 0.74

// Stored modelname (without quotes): "c:/sierra/Half-Life/valve/models/torch1.mdl"
$modelname "torch1.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "torch1_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bone01" -2.19 -2.21 -0.02 2.22 2.19 15.86
$hbox 0 "Bone02" -2.21 -2.89 -0.29 3.61 3.08 14.91
$hbox 0 "Bone03" -0.29 -0.73 0 2.68 0.77 7.13
$hbox 0 "Bone04" -1.97 -0.73 0 0 0.77 6.5

$sequence "torch1_anim_1" {
	"torch1_anims\torch1_anim_1"
	fps 30
	loop
}
$sequence "torch1_anim_1" {
	"torch1_anims\torch1_anim_1_2"
	fps 30
	loop
}
$sequence "torch1_anim_1" {
	"torch1_anims\torch1_anim_1_3"
	fps 30
	loop
}
$sequence "torch1_anim_1" {
	"torch1_anims\torch1_anim_1_4"
	fps 30
	loop
}
$sequence "torch1_anim_1" {
	"torch1_anims\torch1_anim_1_5"
	fps 30
	loop
}
$sequence "torch1_anim_1" {
	"torch1_anims\torch1_anim_1_6"
	fps 30
	loop
}
$sequence "torch1_anim_1" {
	"torch1_anims\torch1_anim_1_7"
	fps 30
	loop
}
$sequence "torch1_anim_1" {
	"torch1_anims\torch1_anim_1_8"
	fps 30
	loop
}
