// Created by Crowbar 0.74

// Stored modelname (without quotes): "c:\sierra\half-life\gearbox\models\pit_drone_spike.mdl"
$modelname "pit_drone_spike.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "pit_drone_spike_reference"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bone02" -1.06 -8.27 -1.31 1.05 1.2 1.31

$sequence "idle" {
	"pit_drone_spike_anims\idle"
	fps 30
}
