// Created by Crowbar 0.74

// Stored modelname (without quotes): "c:/sierra/half-life/gearbox/models/sprite.mdl"
$modelname "sprite.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "sprite_reference"
}

$flags 0


$attachment 0 "Bone02" 0 0 0

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bone01" -0.86 -0.92 -14.960315 1.13 1.07 0.48

$sequence "circle" {
	"sprite_anims\circle"
	fps 30
}
