// Created by Crowbar 0.74

$modelname "wire_blue24.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "wire_blue(24units)"
}

$flags 0


$attachment 0 "Bone02" 0 0 0

$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bone01" -0.86 -0.92 -22.992582 1.13 1.07 0.48
$hbox 0 "Bone02" -0.86 -0.92 -1.25 1.13 1.07 0

$sequence "idle" {
	"wire_blue24_anims\idle"
	fps 30
	loop
}
