// Created by Crowbar 0.74

$modelname "props_destruction/general_dest_roof_set.mdl"

$bodygroup "body"
{
	studio "general_dest_roof_set.smd"
}


$surfaceprop "concrete"

$contents "solid"

$illumposition 1.194 0.703 -0.247

$cdmaterials "models\props_destruction"
$cdmaterials ""

$attachment "roof_origd" "Origin_direction" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -26.198 -24.291 -7.744 24.792 26.679 7.25

$definebone "Origin_direction" "" 0 0 0.925497 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles8" "" -16.764587 4.683612 -13.401812 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles9" "" 17.033619 4.879868 -18.16206 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_4" "" 0.98124 -2.707647 0.306889 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_5" "" -8.322011 -3.64431 -9.75801 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_2" "" 1.888922 -0.558072 -6.167681 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_3" "" -12.140409 -1.096297 10.57449 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles1" "" 12.174629 2.535737 12.9316 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles2" "" -9.235555 1.293772 -16.299759 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles3" "" 8.424523 2.17605 -19.181374 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles4" "" 16.506884 2.224547 -4.291133 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles5" "" -7.985291 2.681772 7.949795 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles6" "" -19.405365 1.616035 -1.5139 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles7" "" -19.542955 5.405792 -7.679185 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_56" "" -2.642838 -2.218494 10.298401 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_57" "" 7.815586 1.126631 -8.512075 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_58" "" 6.665289 0.181439 -18.461321 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_59" "" -2.565267 0.246878 -4.420884 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles30" "" -6.223362 2.053939 -17.939583 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_54" "" -6.360969 -3.225548 -0.253938 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_94" "" -10.134857 -5.49707 -10.803013 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_91" "" 5.144039 -5.502907 -4.788033 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_90" "" -6.760544 0.340714 -17.628571 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_93" "" -4.924198 -2.416409 6.949158 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_92" "" 9.153193 -3.987473 -14.064962 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_79" "" -9.677929 1.761238 -1.83791 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_78" "" 9.394817 -5.332619 7.299084 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_77" "" -5.559399 -0.893188 -8.762499 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_76" "" 6.12019 -1.963703 -15.033306 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_75" "" 11.129173 -0.40147 -18.630651 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_74" "" -11.298527 1.426765 -10.426306 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_73" "" 4.910427 -6.410103 1.575239 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_72" "" 15.496826 -3.903542 12.502706 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_71" "" 14.989373 -2.28455 7.358703 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_70" "" 14.843159 -2.407288 -10.76698 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_65" "" 1.673051 -0.490054 -7.804936 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_64" "" 2.935392 1.054079 13.529648 73.7893 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_67" "" 11.303448 0.606265 -12.196836 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_66" "" 15.381021 -0.958465 9.571605 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_61" "" -14.554783 0.27692 -3.081803 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_60" "" -2.557674 0.962657 -16.886333 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_63" "" 3.341255 2.320247 -2.381267 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_62" "" -5.503136 -0.752873 2.879212 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles27" "" -14.90617 3.510831 -8.744062 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles26" "" 14.680106 3.356816 7.639591 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles25" "" 4.422133 5.098059 -12.450762 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles24" "" -18.133074 2.034258 -16.706602 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_69" "" -8.547714 -0.441535 0.097324 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_1_68" "" 14.127403 -0.222955 -13.580895 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles21" "" -18.588516 1.300111 14.90802 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles20" "" 11.230337 5.344834 -19.173569 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_82" "" 12.244617 -2.005779 -15.14727 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_83" "" 10.339806 0.891422 -17.868704 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_80" "" 5.158466 -0.581944 -6.066855 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_81" "" 11.237904 0.817429 3.569946 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_86" "" 17.696867 -2.686783 2.715912 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_87" "" -3.560274 -3.019535 12.728045 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_84" "" -0.937283 -4.539944 -16.329802 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_85" "" 15.898264 -3.763588 -16.025118 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_88" "" -5.288242 2.296432 -13.10231 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_89" "" -7.112988 -5.896378 7.37327 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_6" "" -8.208834 -5.442492 -0.326002 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_7" "" 1.230376 1.519177 -6.822308 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_68" "" 1.451644 -1.881462 -4.68952 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_69" "" 0.907678 -0.219311 -17.592886 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_64" "" 7.934419 -3.6479 2.678228 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_65" "" 11.966692 -4.724888 -5.980656 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_66" "" 11.946865 -4.488449 -5.676346 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_67" "" 9.500511 0.663349 18.985733 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_60" "" 11.450031 -0.970917 -3.961483 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_61" "" 9.215338 -4.93615 -9.752773 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_62" "" -15.340184 -3.723083 -9.317516 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_63" "" 5.214639 1.243645 7.094234 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles12" "" 9.871571 5.487268 5.018364 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles13" "" 4.371353 3.905987 -2.836201 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles10" "" -9.367222 5.279292 -14.869625 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles11" "" 16.566338 2.611785 -11.302162 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles16" "" 7.344529 5.454868 -19.749176 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles17" "" 16.49699 4.666752 8.003469 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles14" "" -16.585539 3.801447 2.501629 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles15" "" -18.176411 4.563187 6.460039 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_25" "" 11.309397 6.02009 -5.477745 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_24" "" -18.205236 -5.814391 -5.671649 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles18" "" 21.930996 4.290092 13.559453 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles19" "" -7.50748 2.655149 15.941758 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_21" "" -4.26052 -0.774247 -8.928027 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_20" "" -5.399492 -3.351802 -10.581335 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_23" "" 9.660868 -1.876692 -9.730082 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_22" "" -3.199799 -0.010316 -6.753789 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_59" "" -10.223131 1.45076 9.962572 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_58" "" -2.318737 -0.739223 -2.566081 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_8" "" -19.404621 -4.077528 8.314075 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_51" "" 9.659431 -0.628063 9.796107 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_50" "" 7.062722 2.12804 -2.848154 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_53" "" 0.090948 -0.294949 -14.906847 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_9" "" 0.784285 -2.886044 -12.055891 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_55" "" 0.855695 -2.622494 -9.064259 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_27" "" 0.691976 3.469678 -14.187359 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_57" "" 1.633628 0.307617 6.943296 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_56" "" -0.600518 0.08149 17.45813 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_26" "" -6.261048 4.990937 -10.17333 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles29" "" 16.532759 2.702204 2.333994 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles28" "" 8.782673 4.145244 14.722643 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_10" "" -2.282433 -1.746024 -4.093399 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_11" "" -1.405018 -4.675901 -8.29023 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_12" "" -3.463534 -4.407093 -16.052694 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_13" "" 0.842793 -5.118692 6.342357 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_14" "" -15.397963 0.471705 -10.112535 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_15" "" 0.731843 0.31086 -11.609003 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_16" "" 1.567069 -3.170584 -6.807749 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_17" "" -3.103335 -5.866908 -13.122939 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_18" "" -0.605359 -2.375744 -14.692602 0 0 0 0 0 0 0 0 0
$definebone "baked_concrete_newItems_19" "" -3.470205 -3.110971 -7.42442 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles23" "" 3.843082 4.711327 -11.237278 0 0 0 0 0 0 0 0 0
$definebone "baked_shingles22" "" -10.150391 5.534838 0.661062 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_46" "" 13.90304 -4.964222 3.804977 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_47" "" -3.353407 -0.167561 -9.495334 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_44" "" -0.000237 -2.258926 4.47726 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_45" "" 12.846478 -3.339615 17.777227 -45.802719 0 0 0 0 0 0 0 0
$definebone "baked_rubble_42" "" 3.231716 1.473007 -1.409138 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_43" "" -7.30712 -1.316528 -7.93716 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_40" "" 1.883062 -5.834165 8.33655 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_41" "" -6.820864 -2.394494 3.452055 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_48" "" 14.853127 -4.193474 -1.803255 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_52" "" 8.345596 -3.108204 12.201428 0 0 0 0 0 0 0 0 0
$definebone "baked_rubble_49" "" -7.207266 -1.95414 0.955002 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "Origin_direction" position
$bonesaveframe "baked_shingles8" position
$bonesaveframe "baked_shingles9" position
$bonesaveframe "baked_concrete_newItems_4" position
$bonesaveframe "baked_concrete_newItems_5" position
$bonesaveframe "baked_concrete_newItems_2" position
$bonesaveframe "baked_concrete_newItems_3" position
$bonesaveframe "baked_shingles1" position
$bonesaveframe "baked_shingles2" position
$bonesaveframe "baked_shingles3" position
$bonesaveframe "baked_shingles4" position
$bonesaveframe "baked_shingles5" position
$bonesaveframe "baked_shingles6" position
$bonesaveframe "baked_shingles7" position
$bonesaveframe "baked_concrete_1_56" position
$bonesaveframe "baked_concrete_1_57" position
$bonesaveframe "baked_concrete_1_58" position
$bonesaveframe "baked_concrete_1_59" position
$bonesaveframe "baked_shingles30" position
$bonesaveframe "baked_rubble_54" position
$bonesaveframe "baked_rubble_94" position
$bonesaveframe "baked_rubble_91" position
$bonesaveframe "baked_rubble_90" position
$bonesaveframe "baked_rubble_93" position
$bonesaveframe "baked_rubble_92" position
$bonesaveframe "baked_rubble_79" position
$bonesaveframe "baked_rubble_78" position
$bonesaveframe "baked_rubble_77" position
$bonesaveframe "baked_rubble_76" position
$bonesaveframe "baked_rubble_75" position
$bonesaveframe "baked_rubble_74" position
$bonesaveframe "baked_rubble_73" position
$bonesaveframe "baked_rubble_72" position
$bonesaveframe "baked_rubble_71" position
$bonesaveframe "baked_rubble_70" position
$bonesaveframe "baked_concrete_1_65" position
$bonesaveframe "baked_concrete_1_64" position
$bonesaveframe "baked_concrete_1_67" position
$bonesaveframe "baked_concrete_1_66" position
$bonesaveframe "baked_concrete_1_61" position
$bonesaveframe "baked_concrete_1_60" position
$bonesaveframe "baked_concrete_1_63" position
$bonesaveframe "baked_concrete_1_62" position
$bonesaveframe "baked_shingles27" position
$bonesaveframe "baked_shingles26" position
$bonesaveframe "baked_shingles25" position
$bonesaveframe "baked_shingles24" position
$bonesaveframe "baked_concrete_1_69" position
$bonesaveframe "baked_concrete_1_68" position
$bonesaveframe "baked_shingles21" position
$bonesaveframe "baked_shingles20" position
$bonesaveframe "baked_rubble_82" position
$bonesaveframe "baked_rubble_83" position
$bonesaveframe "baked_rubble_80" position
$bonesaveframe "baked_rubble_81" position
$bonesaveframe "baked_rubble_86" position
$bonesaveframe "baked_rubble_87" position
$bonesaveframe "baked_rubble_84" position
$bonesaveframe "baked_rubble_85" position
$bonesaveframe "baked_rubble_88" position
$bonesaveframe "baked_rubble_89" position
$bonesaveframe "baked_concrete_newItems_6" position
$bonesaveframe "baked_concrete_newItems_7" position
$bonesaveframe "baked_rubble_68" position
$bonesaveframe "baked_rubble_69" position
$bonesaveframe "baked_rubble_64" position
$bonesaveframe "baked_rubble_65" position
$bonesaveframe "baked_rubble_66" position
$bonesaveframe "baked_rubble_67" position
$bonesaveframe "baked_rubble_60" position
$bonesaveframe "baked_rubble_61" position
$bonesaveframe "baked_rubble_62" position
$bonesaveframe "baked_rubble_63" position
$bonesaveframe "baked_shingles12" position
$bonesaveframe "baked_shingles13" position
$bonesaveframe "baked_shingles10" position
$bonesaveframe "baked_shingles11" position
$bonesaveframe "baked_shingles16" position
$bonesaveframe "baked_shingles17" position
$bonesaveframe "baked_shingles14" position
$bonesaveframe "baked_shingles15" position
$bonesaveframe "baked_concrete_newItems_25" position
$bonesaveframe "baked_concrete_newItems_24" position
$bonesaveframe "baked_shingles18" position
$bonesaveframe "baked_shingles19" position
$bonesaveframe "baked_concrete_newItems_21" position
$bonesaveframe "baked_concrete_newItems_20" position
$bonesaveframe "baked_concrete_newItems_23" position
$bonesaveframe "baked_concrete_newItems_22" position
$bonesaveframe "baked_rubble_59" position
$bonesaveframe "baked_rubble_58" position
$bonesaveframe "baked_concrete_newItems_8" position
$bonesaveframe "baked_rubble_51" position
$bonesaveframe "baked_rubble_50" position
$bonesaveframe "baked_rubble_53" position
$bonesaveframe "baked_concrete_newItems_9" position
$bonesaveframe "baked_rubble_55" position
$bonesaveframe "baked_concrete_newItems_27" position
$bonesaveframe "baked_rubble_57" position
$bonesaveframe "baked_rubble_56" position
$bonesaveframe "baked_concrete_newItems_26" position
$bonesaveframe "baked_shingles29" position
$bonesaveframe "baked_shingles28" position
$bonesaveframe "baked_concrete_newItems_10" position
$bonesaveframe "baked_concrete_newItems_11" position
$bonesaveframe "baked_concrete_newItems_12" position
$bonesaveframe "baked_concrete_newItems_13" position
$bonesaveframe "baked_concrete_newItems_14" position
$bonesaveframe "baked_concrete_newItems_15" position
$bonesaveframe "baked_concrete_newItems_16" position
$bonesaveframe "baked_concrete_newItems_17" position
$bonesaveframe "baked_concrete_newItems_18" position
$bonesaveframe "baked_concrete_newItems_19" position
$bonesaveframe "baked_shingles23" position
$bonesaveframe "baked_shingles22" position
$bonesaveframe "baked_rubble_46" position
$bonesaveframe "baked_rubble_47" position
$bonesaveframe "baked_rubble_44" position
$bonesaveframe "baked_rubble_45" position
$bonesaveframe "baked_rubble_42" position
$bonesaveframe "baked_rubble_43" position
$bonesaveframe "baked_rubble_40" position
$bonesaveframe "baked_rubble_41" position
$bonesaveframe "baked_rubble_48" position
$bonesaveframe "baked_rubble_52" position
$bonesaveframe "baked_rubble_49" position

$sectionframes 30 149

$sequence "ref" {
	"general_dest_roof_set_anims\ref.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "idle" {
	"general_dest_roof_set_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_00a" {
	"general_dest_roof_set_anims\set_00a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_00b" {
	"general_dest_roof_set_anims\set_00b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_01a" {
	"general_dest_roof_set_anims\set_01a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_01b" {
	"general_dest_roof_set_anims\set_01b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_02a" {
	"general_dest_roof_set_anims\set_02a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_02b" {
	"general_dest_roof_set_anims\set_02b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_03a" {
	"general_dest_roof_set_anims\set_03a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_03b" {
	"general_dest_roof_set_anims\set_03b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_04a" {
	"general_dest_roof_set_anims\set_04a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_04b" {
	"general_dest_roof_set_anims\set_04b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_05a" {
	"general_dest_roof_set_anims\set_05a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_05b" {
	"general_dest_roof_set_anims\set_05b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_06a" {
	"general_dest_roof_set_anims\set_06a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_06b" {
	"general_dest_roof_set_anims\set_06b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_07a" {
	"general_dest_roof_set_anims\set_07a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_07b" {
	"general_dest_roof_set_anims\set_07b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_08a" {
	"general_dest_roof_set_anims\set_08a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_08b" {
	"general_dest_roof_set_anims\set_08b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_09a" {
	"general_dest_roof_set_anims\set_09a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_09b" {
	"general_dest_roof_set_anims\set_09b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_10a" {
	"general_dest_roof_set_anims\set_10a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_10b" {
	"general_dest_roof_set_anims\set_10b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_11a" {
	"general_dest_roof_set_anims\set_11a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_11b" {
	"general_dest_roof_set_anims\set_11b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_12a" {
	"general_dest_roof_set_anims\set_12a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_12b" {
	"general_dest_roof_set_anims\set_12b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_13a" {
	"general_dest_roof_set_anims\set_13a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_13b" {
	"general_dest_roof_set_anims\set_13b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_14a" {
	"general_dest_roof_set_anims\set_14a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_14b" {
	"general_dest_roof_set_anims\set_14b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_15a" {
	"general_dest_roof_set_anims\set_15a.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "set_15b" {
	"general_dest_roof_set_anims\set_15b.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment roof_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "gen_hit_up start_at_attachment roof_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
