// Created by Crowbar 0.74

$modelname "props_destruction/general_dest_concrete_set.mdl"

$bodygroup "body"
{
	studio "general_dest_concrete_set.smd"
}


$surfaceprop "metal"

$contents "solid"

$illumposition -3.822 5.078 -2.824

$cdmaterials "models\props_destruction"
$cdmaterials ""

$attachment "conc_origd" "Origin_direction" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -35.389 -27.662 -14.785 25.234 20.017 9.138

$definebone "Origin_direction" "" 0 0 11.25 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_16_MBLoc" "" -0.287319 -8.07506 1.928765 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_26_MBLoc" "" -6.261047 4.999084 -10.173331 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_69_MBLoc" "" -3.199799 -0.010316 -6.753789 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_23_MBLoc" "" -1.15006 -1.257997 7.97354 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_10_MBLoc" "" -6.126597 -2.271691 7.844934 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_37_MBLoc" "" -7.623837 -0.184758 -17.478287 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_18_MBLoc" "" 10.764441 -0.637033 5.558411 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_18_MBLoc" "" -7.307589 -3.057654 2.347077 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_55_MBLoc" "" -1.876014 -2.595416 -6.539629 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_21_MBLoc" "" 0.673498 3.435726 -14.187359 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_29_MBLoc" "" -0.724515 -2.386729 10.156813 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_20_MBLoc" "" 11.304328 0.594456 -4.052289 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_49_MBLoc" "" -4.425296 -0.142281 -16.204157 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_71_MBLoc" "" -5.469477 -1.419278 -0.374997 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_16_MBLoc" "" 0.744841 -8.830256 -18.597511 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_22_MBLoc" "" -4.517265 -9.092265 5.537123 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_50_MBLoc" "" -3.962528 0.601096 7.95656 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_11_MBLoc" "" -11.852607 -7.095746 -14.971189 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_34_MBLoc" "" -0.929351 -0.781341 -6.19478 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_12_MBLoc" "" -2.99894 -2.635384 -4.346958 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_36_MBLoc" "" -0.60536 -2.375744 -14.692603 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_65_MBLoc" "" -1.396971 -2.766251 -8.381141 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_28_MBLoc" "" -10.539604 -5.387695 -12.485662 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_6_MBLoc" "" -3.450104 -3.844487 14.790927 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_48_MBLoc" "" -10.557272 -5.527755 -5.254356 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_32_MBLoc" "" -10.915125 -2.448045 13.162571 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_33_MBLoc" "" 9.231439 -3.61446 -1.392712 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_40_MBLoc" "" 0.810092 -2.783418 -5.532722 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_33_MBLoc" "" 6.384151 -1.631805 11.814228 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_12_MBLoc" "" 3.477521 -8.965746 -5.24407 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_63_MBLoc" "" -0.541139 -1.9583 2.19326 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_2_MBLoc" "" 5.360678 3.089343 10.526508 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_27_MBLoc" "" -6.992485 -5.835119 14.847159 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_54_MBLoc" "" -0.179579 -1.311731 -1.049149 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_4_MBLoc" "" -10.874487 -8.261217 3.866898 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_25_MBLoc" "" -3.103333 -5.866908 -13.122938 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_1_MBLoc" "" 12.856676 -5.875854 8.054982 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_59_MBLoc" "" -2.851591 -4.780866 2.709902 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_12_MBLoc" "" 0.842793 -5.118693 6.342359 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_1_MBLoc" "" 0.054429 -9.773726 -7.975583 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_62_MBLoc" "" -5.737293 -8.595178 13.589659 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_7_MBLoc" "" 4.284243 -2.100933 1.90525 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_17_MBLoc" "" 11.009932 -2.141997 2.100645 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_4_MBLoc" "" -8.322008 -3.64431 -9.75801 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_70_MBLoc" "" 0.20504 5.22136 -17.274258 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_2_MBLoc" "" 0.075828 -1.325624 -7.027023 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_11_MBLoc" "" -3.463534 -4.407093 -16.052696 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_41_MBLoc" "" -1.417755 -1.548215 -4.309315 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_24_MBLoc" "" 5.452278 -3.567572 12.676774 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_74_MBLoc" "" 1.100796 -3.119546 -11.106707 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_13_MBLoc" "" -9.53355 0.471705 -10.112537 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_9_MBLoc" "" -2.282433 -1.746024 -4.093395 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_68_MBLoc" "" 2.141872 1.388599 0.420171 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_14_MBLoc" "" 0.731843 0.310859 -11.609004 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_7_MBLoc" "" -11.934873 -4.075589 -2.106433 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_14_MBLoc" "" 0.96585 -10.852264 11.259468 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_28_MBLoc" "" 0.496364 -0.256656 -2.943862 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_15_MBLoc" "" -10.843049 -1.240636 -2.264224 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_38_MBLoc" "" -0.150126 0.257164 -13.487519 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_19_MBLoc" "" -6.461676 -6.979063 -5.671649 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_53_MBLoc" "" -1.342998 -6.637565 -1.357581 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_26_MBLoc" "" 12.573425 -3.222363 -8.394188 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_22_MBLoc" "" 6.932134 -0.106165 0.330212 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_8_MBLoc" "" 0.784285 -2.886044 -12.05589 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_47_MBLoc" "" -6.076067 -1.428479 -18.432613 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_56_MBLoc" "" -8.832991 -1.517537 3.032722 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_46_MBLoc" "" -3.470206 -3.110971 -7.424419 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_27_MBLoc" "" -3.802463 -0.483412 -14.73483 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_37_MBLoc" "" -6.410721 -6.340672 -15.303814 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_8_MBLoc" "" -8.07646 -6.345669 -8.435143 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_9_MBLoc" "" 2.750635 1.434161 6.338632 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_29_MBLoc" "" 8.140402 1.276614 -6.714768 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_3_MBLoc" "" 0.981241 -2.707647 0.306889 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_58_MBLoc" "" -5.399492 -3.351802 -10.581335 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_15_MBLoc" "" 12.751193 -3.260772 2.486247 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_61_MBLoc" "" -5.470761 -1.790143 -2.161706 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_60_MBLoc" "" -7.499877 -1.559501 -2.001084 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_20_MBLoc" "" -6.757382 -0.888562 -0.941643 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_45_MBLoc" "" 2.005213 -6.751465 -9.405521 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_35_MBLoc" "" -9.073204 -0.625073 -8.355967 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_31_MBLoc" "" 11.220648 5.97376 -5.514739 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_5_MBLoc" "" 3.534726 -5.442492 -0.326003 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_10_MBLoc" "" 10.636371 -4.462889 -0.258395 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_39_MBLoc" "" 5.242252 -7.074311 16.099827 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_51_MBLoc" "" -0.664246 -3.029551 4.384606 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_1_MBLoc" "" 1.888923 -0.558072 -6.167683 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_43_MBLoc" "" -0.087359 -9.968849 -9.73008 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_30_MBLoc" "" -5.323812 1.089372 -18.08083 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_25_MBLoc" "" -4.501587 -1.783866 -3.37972 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_21_MBLoc" "" -5.032959 -1.084849 -14.24279 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_72_MBLoc" "" 0.00861 -3.050106 1.395232 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_73_MBLoc" "" -9.642035 -8.046715 -19.627724 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_52_MBLoc" "" -2.87015 3.999327 -0.357957 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_42_MBLoc" "" -3.363384 -2.210212 0.60134 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_39_MBLoc" "" 0.85039 0.851383 -6.892642 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_23_MBLoc" "" -8.99146 4.878048 8.444877 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_31_MBLoc" "" -2.72608 -6.520373 -5.738552 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_11_MBLoc" "" 3.448853 -6.245413 -3.009525 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_67_MBLoc" "" -6.475077 3.654288 -5.928169 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_14_MBLoc" "" -7.163067 -0.24063 12.356787 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_36_MBLoc" "" -0.293209 -2.117959 -13.752008 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_16_MBLoc" "" 1.567069 -3.170584 -6.807751 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_5_MBLoc" "" -10.658249 2.633621 2.172365 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_9_MBLoc" "" -0.510385 3.649933 -9.152468 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_32_MBLoc" "" -4.711471 -10.354914 -20.181387 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_19_MBLoc" "" -10.92642 3.437695 9.002989 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_5_MBLoc" "" -10.01311 -1.749054 -12.414475 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_10_MBLoc" "" -1.405017 -4.675901 -8.290229 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_3_MBLoc" "" 6.257715 1.844222 -0.644273 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_57_MBLoc" "" 2.49682 -5.798657 11.671879 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_44_MBLoc" "" -6.172084 6.358871 1.382849 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_13_MBLoc" "" 0.243826 -2.586528 3.525126 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_17_MBLoc" "" -4.047277 3.083602 -4.025006 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_30_MBLoc" "" 9.56194 -0.770173 0.012921 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_6_MBLoc" "" -10.708386 -4.849997 -18.741852 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_35_MBLoc" "" -3.969423 -4.736401 0.037695 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_64_MBLoc" "" -4.260521 -0.774247 -8.928028 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_34_MBLoc" "" -9.608921 -4.850079 -5.943151 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_4_MBLoc" "" 2.923975 -5.077462 -4.11375 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_24_MBLoc" "" 0.453634 -9.284713 -8.829441 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_8_MBLoc" "" -1.928324 0.786047 -9.410177 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_3_MBLoc" "" 1.843064 -1.960409 1.892041 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_7_MBLoc" "" -7.66106 -8.03218 8.314074 0 0 0 0 0 0 0 0 0
$definebone "concrete_4_6_MBLoc" "" 1.230377 1.519178 -6.822307 0 0 0 0 0 0 0 0 0
$definebone "concrete_2_66_MBLoc" "" -9.951306 -0.590021 8.416938 0 0 0 0 0 0 0 0 0
$definebone "concrete_3_13_MBLoc" "" -6.387291 -1.010367 -15.415941 0 0 0 0 0 0 0 0 0


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "Origin_direction" position rotation
$bonesaveframe "concrete_3_16_MBLoc" position rotation
$bonesaveframe "concrete_2_26_MBLoc" position rotation
$bonesaveframe "concrete_2_69_MBLoc" position rotation
$bonesaveframe "concrete_2_23_MBLoc" position rotation
$bonesaveframe "concrete_2_10_MBLoc" position rotation
$bonesaveframe "concrete_2_37_MBLoc" position rotation
$bonesaveframe "concrete_3_18_MBLoc" position rotation
$bonesaveframe "concrete_2_18_MBLoc" position rotation
$bonesaveframe "concrete_2_55_MBLoc" position rotation
$bonesaveframe "concrete_3_21_MBLoc" position rotation
$bonesaveframe "concrete_2_29_MBLoc" position rotation
$bonesaveframe "concrete_3_20_MBLoc" position rotation
$bonesaveframe "concrete_2_49_MBLoc" position rotation
$bonesaveframe "concrete_2_71_MBLoc" position rotation
$bonesaveframe "concrete_2_16_MBLoc" position rotation
$bonesaveframe "concrete_2_22_MBLoc" position rotation
$bonesaveframe "concrete_2_50_MBLoc" position rotation
$bonesaveframe "concrete_3_11_MBLoc" position rotation
$bonesaveframe "concrete_2_34_MBLoc" position rotation
$bonesaveframe "concrete_2_12_MBLoc" position rotation
$bonesaveframe "concrete_2_36_MBLoc" position rotation
$bonesaveframe "concrete_2_65_MBLoc" position rotation
$bonesaveframe "concrete_3_28_MBLoc" position rotation
$bonesaveframe "concrete_2_6_MBLoc" position rotation
$bonesaveframe "concrete_2_48_MBLoc" position rotation
$bonesaveframe "concrete_3_32_MBLoc" position rotation
$bonesaveframe "concrete_3_33_MBLoc" position rotation
$bonesaveframe "concrete_2_40_MBLoc" position rotation
$bonesaveframe "concrete_2_33_MBLoc" position rotation
$bonesaveframe "concrete_3_12_MBLoc" position rotation
$bonesaveframe "concrete_2_63_MBLoc" position rotation
$bonesaveframe "concrete_4_2_MBLoc" position rotation
$bonesaveframe "concrete_3_27_MBLoc" position rotation
$bonesaveframe "concrete_2_54_MBLoc" position rotation
$bonesaveframe "concrete_2_4_MBLoc" position rotation
$bonesaveframe "concrete_2_25_MBLoc" position rotation
$bonesaveframe "concrete_3_1_MBLoc" position rotation
$bonesaveframe "concrete_2_59_MBLoc" position rotation
$bonesaveframe "concrete_4_12_MBLoc" position rotation
$bonesaveframe "concrete_2_1_MBLoc" position rotation
$bonesaveframe "concrete_2_62_MBLoc" position rotation
$bonesaveframe "concrete_3_7_MBLoc" position rotation
$bonesaveframe "concrete_3_17_MBLoc" position rotation
$bonesaveframe "concrete_4_4_MBLoc" position rotation
$bonesaveframe "concrete_2_70_MBLoc" position rotation
$bonesaveframe "concrete_2_2_MBLoc" position rotation
$bonesaveframe "concrete_4_11_MBLoc" position rotation
$bonesaveframe "concrete_2_41_MBLoc" position rotation
$bonesaveframe "concrete_3_24_MBLoc" position rotation
$bonesaveframe "concrete_2_74_MBLoc" position rotation
$bonesaveframe "concrete_4_13_MBLoc" position rotation
$bonesaveframe "concrete_4_9_MBLoc" position rotation
$bonesaveframe "concrete_2_68_MBLoc" position rotation
$bonesaveframe "concrete_4_14_MBLoc" position rotation
$bonesaveframe "concrete_2_7_MBLoc" position rotation
$bonesaveframe "concrete_2_14_MBLoc" position rotation
$bonesaveframe "concrete_2_28_MBLoc" position rotation
$bonesaveframe "concrete_2_15_MBLoc" position rotation
$bonesaveframe "concrete_2_38_MBLoc" position rotation
$bonesaveframe "concrete_2_19_MBLoc" position rotation
$bonesaveframe "concrete_2_53_MBLoc" position rotation
$bonesaveframe "concrete_3_26_MBLoc" position rotation
$bonesaveframe "concrete_3_22_MBLoc" position rotation
$bonesaveframe "concrete_4_8_MBLoc" position rotation
$bonesaveframe "concrete_2_47_MBLoc" position rotation
$bonesaveframe "concrete_2_56_MBLoc" position rotation
$bonesaveframe "concrete_2_46_MBLoc" position rotation
$bonesaveframe "concrete_2_27_MBLoc" position rotation
$bonesaveframe "concrete_3_37_MBLoc" position rotation
$bonesaveframe "concrete_3_8_MBLoc" position rotation
$bonesaveframe "concrete_3_9_MBLoc" position rotation
$bonesaveframe "concrete_3_29_MBLoc" position rotation
$bonesaveframe "concrete_4_3_MBLoc" position rotation
$bonesaveframe "concrete_2_58_MBLoc" position rotation
$bonesaveframe "concrete_3_15_MBLoc" position rotation
$bonesaveframe "concrete_2_61_MBLoc" position rotation
$bonesaveframe "concrete_2_60_MBLoc" position rotation
$bonesaveframe "concrete_2_20_MBLoc" position rotation
$bonesaveframe "concrete_2_45_MBLoc" position rotation
$bonesaveframe "concrete_3_35_MBLoc" position rotation
$bonesaveframe "concrete_3_31_MBLoc" position rotation
$bonesaveframe "concrete_4_5_MBLoc" position rotation
$bonesaveframe "concrete_3_10_MBLoc" position rotation
$bonesaveframe "concrete_3_39_MBLoc" position rotation
$bonesaveframe "concrete_2_51_MBLoc" position rotation
$bonesaveframe "concrete_4_1_MBLoc" position rotation
$bonesaveframe "concrete_2_43_MBLoc" position rotation
$bonesaveframe "concrete_2_30_MBLoc" position rotation
$bonesaveframe "concrete_3_25_MBLoc" position rotation
$bonesaveframe "concrete_2_21_MBLoc" position rotation
$bonesaveframe "concrete_2_72_MBLoc" position rotation
$bonesaveframe "concrete_2_73_MBLoc" position rotation
$bonesaveframe "concrete_2_52_MBLoc" position rotation
$bonesaveframe "concrete_2_42_MBLoc" position rotation
$bonesaveframe "concrete_2_39_MBLoc" position rotation
$bonesaveframe "concrete_3_23_MBLoc" position rotation
$bonesaveframe "concrete_2_31_MBLoc" position rotation
$bonesaveframe "concrete_2_11_MBLoc" position rotation
$bonesaveframe "concrete_2_67_MBLoc" position rotation
$bonesaveframe "concrete_3_14_MBLoc" position rotation
$bonesaveframe "concrete_3_36_MBLoc" position rotation
$bonesaveframe "concrete_4_16_MBLoc" position rotation
$bonesaveframe "concrete_2_5_MBLoc" position rotation
$bonesaveframe "concrete_2_9_MBLoc" position rotation
$bonesaveframe "concrete_2_32_MBLoc" position rotation
$bonesaveframe "concrete_3_19_MBLoc" position rotation
$bonesaveframe "concrete_3_5_MBLoc" position rotation
$bonesaveframe "concrete_4_10_MBLoc" position rotation
$bonesaveframe "concrete_2_3_MBLoc" position rotation
$bonesaveframe "concrete_2_57_MBLoc" position rotation
$bonesaveframe "concrete_2_44_MBLoc" position rotation
$bonesaveframe "concrete_2_13_MBLoc" position rotation
$bonesaveframe "concrete_2_17_MBLoc" position rotation
$bonesaveframe "concrete_3_30_MBLoc" position rotation
$bonesaveframe "concrete_3_6_MBLoc" position rotation
$bonesaveframe "concrete_2_35_MBLoc" position rotation
$bonesaveframe "concrete_2_64_MBLoc" position rotation
$bonesaveframe "concrete_3_34_MBLoc" position rotation
$bonesaveframe "concrete_3_4_MBLoc" position rotation
$bonesaveframe "concrete_2_24_MBLoc" position rotation
$bonesaveframe "concrete_2_8_MBLoc" position rotation
$bonesaveframe "concrete_3_3_MBLoc" position rotation
$bonesaveframe "concrete_4_7_MBLoc" position rotation
$bonesaveframe "concrete_4_6_MBLoc" position rotation
$bonesaveframe "concrete_2_66_MBLoc" position rotation
$bonesaveframe "concrete_3_13_MBLoc" position rotation

$sectionframes 30 148

$sequence "ref" {
	"general_dest_concrete_set_anims\ref.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "idle" {
	"general_dest_concrete_set_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "up_100" {
	"general_dest_concrete_set_anims\up_100.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment conc_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "gen_hit_up start_at_attachment conc_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "zpos_100" {
	"general_dest_concrete_set_anims\zpos_100.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment conc_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "gen_hit_up start_at_attachment conc_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "zpos_end" {
	"general_dest_concrete_set_anims\zpos_end.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "zpos_g472_120" {
	"general_dest_concrete_set_anims\zpos_g472_120.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "gen_dest_fireball start_at_attachment conc_origd" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 0 "gen_hit_up start_at_attachment conc_origd" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "zpos_g472_end" {
	"general_dest_concrete_set_anims\zpos_g472_end.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "zposhard_150" {
	"general_dest_concrete_set_anims\zposhard_150.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "zposhard_end" {
	"general_dest_concrete_set_anims\zposhard_end.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}
